// Integration catalogue extracted from reevo.ai/integrations (page chunk, 2026-09-29).
// Row: [name, pillar, category, website, featured]
export const INTEGRATIONS = [
  ["Abstract API","Find","Data & Enrichment","https://abstractapi.com"],
  ["AccuWeather","Find","Data & Enrichment","https://accuweather.com"],
  ["Add to CRM","Find","Data & Enrichment","https://addtocrm.com"],
  ["Adzuna","Find","Data & Enrichment","https://adzuna.com"],
  ["AnyMailFinder","Find","Data & Enrichment","https://anymailfinder.com"],
  ["Apify","Find","Data & Enrichment","https://apify.com"],
  ["AWS Data Exchange","Find","Data & Enrichment","https://amazon.com"],
  ["Badger Maps","Find","Data & Enrichment","https://badgermapping.com"],
  ["Bitscale","Find","Data & Enrichment","https://bitscale.ai"],
  ["Bouncer","Find","Data & Enrichment","https://usebouncer.com"],
  ["Browserbase","Find","Data & Enrichment","https://browserbase.com"],
  ["Clay","Find","Data & Enrichment","https://clay.com",1],
  ["Clearout","Find","Data & Enrichment","https://clearout.io"],
  ["Cognism","Find","Data & Enrichment","https://cognism.com"],
  ["CompanyData","Find","Data & Enrichment","https://companydata.com"],
  ["Craft.co","Find","Data & Enrichment","https://craft.co"],
  ["Crunchbase","Find","Data & Enrichment","https://crunchbase.com"],
  ["Dealroom","Find","Data & Enrichment","https://dealroom.co"],
  ["DeBounce","Find","Data & Enrichment","https://debounce.io"],
  ["Diffbot","Find","Data & Enrichment","https://diffbot.com"],
  ["Docsumo","Find","Data & Enrichment","https://docsumo.com"],
  ["Dropcontact","Find","Data & Enrichment","https://dropcontact.io"],
  ["Dun & Bradstreet Direct+","Find","Data & Enrichment","https://dnb.com"],
  ["eCore Enrichment","Find","Data & Enrichment","https://ecoreservice.com"],
  ["Emailable","Find","Data & Enrichment","https://emailable.com"],
  ["Enigma (Businesses API)","Find","Data & Enrichment","https://enigma.com"],
  ["Enrich.so","Find","Data & Enrichment","https://enrich.so"],
  ["Exa","Find","Data & Enrichment","https://exa.ai"],
  ["Experian Business Information","Find","Data & Enrichment","https://experian.com"],
  ["Explorium","Find","Data & Enrichment","https://explorium.ai"],
  ["Fantastic Jobs (fantastic.jobs)","Find","Data & Enrichment","https://fantastic.jobs"],
  ["Findymail","Find","Data & Enrichment","https://findymail.com"],
  ["Firecrawl","Find","Data & Enrichment","https://firecrawl.dev"],
  ["Forager","Find","Data & Enrichment","https://forager.ai"],
  ["FullContact","Find","Data & Enrichment","https://fullcontact.com"],
  ["FullEnrich","Find","Data & Enrichment","https://fullenrich.com"],
  ["GeoMaps","Find","Data & Enrichment","https://geomaps.co"],
  ["GetProspect","Find","Data & Enrichment","https://getprospect.io"],
  ["Global Database","Find","Data & Enrichment","https://globaldatabase.com"],
  ["Google Maps","Find","Data & Enrichment","https://google.com"],
  ["Harmonic","Find","Data & Enrichment","https://harmonic.ai"],
  ["HERE","Find","Data & Enrichment","https://here.com"],
  ["HG Insights","Find","Data & Enrichment","https://hginsights.com"],
  ["Hunter.io","Find","Data & Enrichment","https://hunter.io"],
  ["Icypeas","Find","Data & Enrichment","https://icypeas.com"],
  ["InfobelPRO","Find","Data & Enrichment","https://infobelpro.com"],
  ["Jina AI (Reader / Search)","Find","Data & Enrichment","https://jina.ai"],
  ["LeadIQ","Find","Data & Enrichment","https://leadiq.com"],
  ["LeadMagic","Find","Data & Enrichment","https://leadmagic.io"],
  ["Live Data Technologies","Find","Data & Enrichment","https://livedatatechnologies.com"],
  ["LlamaParse (LlamaIndex)","Find","Data & Enrichment","https://llamaindex.ai"],
  ["Lusha","Find","Data & Enrichment","https://lusha.com"],
  ["Lytics","Find","Data & Enrichment","https://lytics.com"],
  ["MailTester.com (email verifier)","Find","Data & Enrichment","https://mailtester.com"],
  ["Mapbox","Find","Data & Enrichment","https://mapbox.com"],
  ["Mendable (Firecrawl lineage)","Find","Data & Enrichment","https://mendable.ai"],
  ["MillionVerifier","Find","Data & Enrichment","https://millionverifier.com"],
  ["Mindee","Find","Data & Enrichment","https://mindee.com"],
  ["Nanonets","Find","Data & Enrichment","https://nanonets.com"],
  ["NeverBounce","Find","Data & Enrichment","https://neverbounce.com"],
  ["Numverify","Find","Data & Enrichment","https://numverify.com"],
  ["Ocean.io","Find","Data & Enrichment","https://ocean.io"],
  ["OpenWeather","Find","Data & Enrichment","https://openweathermap.org"],
  ["Paradigm","Find","Data & Enrichment","https://paradigmai.com"],
  ["People Data Labs","Find","Data & Enrichment","https://peopledatalabs.com"],
  ["Phantombuster","Find","Data & Enrichment","https://phantombuster.com"],
  ["Pipecorn","Find","Data & Enrichment","https://pipecorn.com"],
  ["Precisely","Find","Data & Enrichment","https://precisely.com"],
  ["Prospeo","Find","Data & Enrichment","https://prospeo.io"],
  ["Reducto","Find","Data & Enrichment","https://reducto.ai"],
  ["RocketReach","Find","Data & Enrichment","https://rocketreach.co"],
  ["Rossum","Find","Data & Enrichment","https://rossum.ai"],
  ["Sansan","Find","Data & Enrichment","https://sansan.com"],
  ["Scrapfly","Find","Data & Enrichment","https://scrapfly.io"],
  ["SerpApi (Google Jobs API)","Find","Data & Enrichment","https://serpapi.com"],
  ["SigParser","Find","Data & Enrichment","https://sigparser.com"],
  ["Skrapp","Find","Data & Enrichment","https://skrapp.io"],
  ["Smarty","Find","Data & Enrichment","https://smarty.com"],
  ["Specter","Find","Data & Enrichment","https://tryspecter.com"],
  ["StoreInspect","Find","Data & Enrichment","https://storeinspect.com"],
  ["Sumble","Find","Data & Enrichment","https://sumble.com"],
  ["T2A.io TPS/CTPS API","Find","Data & Enrichment","https://t2a.io"],
  ["Tavily","Find","Data & Enrichment","https://tavily.com"],
  ["Tensorlake","Find","Data & Enrichment","https://tensorlake.ai"],
  ["The Swarm","Find","Data & Enrichment","https://theswarm.com"],
  ["Tomba","Find","Data & Enrichment","https://tomba.io"],
  ["Tomorrow.io","Find","Data & Enrichment","https://tomorrow.io"],
  ["TPSCheck.uk","Find","Data & Enrichment","https://tpscheck.uk"],
  ["Trestle","Find","Data & Enrichment","https://trestleiq.com"],
  ["Unstructured","Find","Data & Enrichment","https://unstructured.io"],
  ["UpLead","Find","Data & Enrichment","https://uplead.com"],
  ["Verifalia","Find","Data & Enrichment","https://verifalia.com"],
  ["Veriphone","Find","Data & Enrichment","https://veriphone.io"],
  ["Voila Norbert","Find","Data & Enrichment","https://voilanorbert.com"],
  ["what3words","Find","Data & Enrichment","https://what3words.com"],
  ["WhoisXML API","Find","Data & Enrichment","https://whoisxmlapi.com"],
  ["Wiza","Find","Data & Enrichment","https://wiza.co"],
  ["Yelp Fusion","Find","Data & Enrichment","https://yelp.com"],
  ["Zephira.ai","Find","Data & Enrichment","https://zephira.ai"],
  ["Zyte","Find","Data & Enrichment","https://zyte.com"],
  ["6sense","Find","Intent & Market Signals","https://6sense.com"],
  ["Albacross","Find","Intent & Market Signals","https://albacross.com"],
  ["Alpha Vantage","Find","Intent & Market Signals","https://alphavantage.co"],
  ["AusTender","Find","Intent & Market Signals","https://tenders.gov.au"],
  ["Benzinga","Find","Intent & Market Signals","https://benzinga.com"],
  ["Bound","Find","Intent & Market Signals","https://bound.co"],
  ["CB Insights","Find","Intent & Market Signals","https://cbinsights.com"],
  ["Coinbase","Find","Intent & Market Signals","https://coinbase.com"],
  ["Column","Find","Intent & Market Signals","https://column.com"],
  ["Common Room","Find","Intent & Market Signals","https://commonroom.io"],
  ["Companies House","Find","Intent & Market Signals","https://company-information.service.gov.uk"],
  ["Contracts Finder (UK)","Find","Intent & Market Signals","https://contractsfinder.service.gov.uk"],
  ["Crossbeam (incl. Reveal)","Find","Intent & Market Signals","https://crossbeam.com"],
  ["Dealfront","Find","Intent & Market Signals","https://dealfront.com"],
  ["Demandbase","Find","Intent & Market Signals","https://demandbase.com"],
  ["Enlyft","Find","Intent & Market Signals","https://enlyft.com"],
  ["EODHD (EOD Historical Data)","Find","Intent & Market Signals","https://eodhd.com"],
  ["Factors.ai","Find","Intent & Market Signals","https://factors.ai"],
  ["Find a Tender (UK)","Find","Intent & Market Signals","https://find-tender.service.gov.uk"],
  ["Finnhub","Find","Intent & Market Signals","https://finnhub.io"],
  ["GDELT Project","Find","Intent & Market Signals","https://gdeltproject.org"],
  ["GovSpend","Find","Intent & Market Signals","https://govspend.com"],
  ["HigherGov","Find","Intent & Market Signals","https://highergov.com"],
  ["Intrinio","Find","Intent & Market Signals","https://intrinio.com"],
  ["Kickfire","Find","Intent & Market Signals","https://kickfire.com"],
  ["Knock2","Find","Intent & Market Signals","https://knock2.ai"],
  ["KVK API (Netherlands)","Find","Intent & Market Signals","https://kvk.nl"],
  ["Kyckr","Find","Intent & Market Signals","https://kyckr.com"],
  ["Lead Forensics","Find","Intent & Market Signals","https://leadforensics.com"],
  ["MadKudu","Find","Intent & Market Signals","https://madkudu.com"],
  ["Massive","Find","Intent & Market Signals","https://massive.com"],
  ["MATAGI","Find","Intent & Market Signals","https://matagi.ai"],
  ["Method Financial","Find","Intent & Market Signals","https://methodfi.com"],
  ["MX","Find","Intent & Market Signals","https://mx.com"],
  ["Octolens","Find","Intent & Market Signals","https://octolens.com"],
  ["OpenCorporates","Find","Intent & Market Signals","https://opencorporates.com"],
  ["OpenSanctions","Find","Intent & Market Signals","https://opensanctions.org"],
  ["Oppy","Find","Intent & Market Signals","https://oppyone.com"],
  ["Plaid","Find","Intent & Market Signals","https://plaid.com"],
  ["PredictLeads","Find","Intent & Market Signals","https://predictleads.com"],
  ["Preqin","Find","Intent & Market Signals","https://preqin.com"],
  ["Refinitiv / LSEG Data Platform","Find","Intent & Market Signals","https://lseg.com"],
  ["reodotdev","Find","Intent & Market Signals","https://reo.dev"],
  ["Salespanel","Find","Intent & Market Signals","https://salespanel.io"],
  ["SAM.gov","Find","Intent & Market Signals","https://sam.gov"],
  ["SEC EDGAR","Find","Intent & Market Signals","https://sec.gov"],
  ["Snitcher","Find","Intent & Market Signals","https://snitcher.com"],
  ["SourceForge","Find","Intent & Market Signals","https://sourceforge.net"],
  ["TED","Find","Intent & Market Signals","https://europa.eu"],
  ["TenderNed","Find","Intent & Market Signals","https://tenderned.nl"],
  ["TheirStack","Find","Intent & Market Signals","https://theirstack.com"],
  ["Treasury Prime","Find","Intent & Market Signals","https://treasuryprime.com"],
  ["TrustRadius","Find","Intent & Market Signals","https://trustradius.com"],
  ["Twelve Data","Find","Intent & Market Signals","https://twelvedata.com"],
  ["USAspending","Find","Intent & Market Signals","https://usaspending.gov"],
  ["UserGems","Find","Intent & Market Signals","https://usergems.com"],
  ["Veck","Find","Intent & Market Signals","https://theveck.com"],
  ["Warmly","Find","Intent & Market Signals","https://warmly.ai"],
  ["ZoomInfo Intent","Find","Intent & Market Signals","https://zoominfo.com"],
  ["123FormBuilder","Find","Lead Capture","https://123formbuilder.com"],
  ["Basin","Find","Lead Capture","https://usebasin.com"],
  ["Cal.com (routing forms)","Find","Lead Capture","https://cal.com"],
  ["Chili Piper Distro","Find","Lead Capture","https://chilipiper.com"],
  ["Cognito Forms","Find","Lead Capture","https://cognitoforms.com"],
  ["ConvertFlow","Find","Lead Capture","https://convertflow.com"],
  ["Dimedove","Find","Lead Capture","https://dimedove.com"],
  ["Distribution Engine (NC Squared)","Find","Lead Capture","https://distributionengine.com"],
  ["Fillout","Find","Lead Capture","https://fillout.com"],
  ["Formaloo","Find","Lead Capture","https://formaloo.com"],
  ["Formsort","Find","Lead Capture","https://formsort.com"],
  ["Formspree","Find","Lead Capture","https://formspree.io"],
  ["Formstack","Find","Lead Capture","https://formstack.com"],
  ["Google Ads Lead Form Extensions (Webhook)","Find","Lead Capture","https://google.com"],
  ["Gravity Forms","Find","Lead Capture","https://gravityforms.com"],
  ["Jotform","Find","Lead Capture","https://jotform.com"],
  ["Leadpages","Find","Lead Capture","https://leadpages.com"],
  ["Olark","Find","Lead Capture","https://olark.com"],
  ["Orbit AI","Find","Lead Capture","https://orbitforms.ai"],
  ["Outgrow","Find","Lead Capture","https://outgrow.co"],
  ["Paperform","Find","Lead Capture","https://paperform.co"],
  ["Perspective (getperspective.ai)","Find","Lead Capture","https://getperspective.ai"],
  ["Pointerpro (formerly Survey Anyplace)","Find","Lead Capture","https://pointerpro.com"],
  ["Tally","Find","Lead Capture","https://tally.so"],
  ["Tapni","Find","Lead Capture","https://tapni.com"],
  ["Typeform","Find","Lead Capture","https://typeform.com"],
  ["WhatConverts","Find","Lead Capture","https://whatconverts.com"],
  ["Wix","Find","Lead Capture","https://wix.com"],
  ["WordPress REST API","Find","Lead Capture","https://wordpress.org"],
  ["Wufoo","Find","Lead Capture","https://wufoo.com"],
  ["AB Tasty","Find","Marketing & Ads","https://abtasty.com"],
  ["Act-On","Find","Marketing & Ads","https://act-on.com"],
  ["ActiveCampaign","Find","Marketing & Ads","https://activecampaign.com"],
  ["Adobe Campaign","Find","Marketing & Ads","https://adobe.com"],
  ["Affise","Find","Marketing & Ads","https://affise.com"],
  ["Agorapulse","Find","Marketing & Ads","https://agorapulse.com"],
  ["Attentive","Find","Marketing & Ads","https://attentive.com"],
  ["Awario","Find","Marketing & Ads","https://awario.com"],
  ["beehiiv","Find","Marketing & Ads","https://beehiiv.com"],
  ["Bizzabo","Find","Marketing & Ads","https://bizzabo.com"],
  ["Bloomreach Engagement","Find","Marketing & Ads","https://bloomreach.com"],
  ["Brandwatch","Find","Marketing & Ads","https://brandwatch.com"],
  ["Braze","Find","Marketing & Ads","https://braze.com"],
  ["Brevo (formerly Sendinblue)","Find","Marketing & Ads","https://brevo.com"],
  ["Buffer","Find","Marketing & Ads","https://buffer.com"],
  ["Campaign Monitor","Find","Marketing & Ads","https://campaignmonitor.com"],
  ["Canva","Find","Marketing & Ads","https://canva.com"],
  ["Cello","Find","Marketing & Ads","https://cello.so"],
  ["CleverTap","Find","Marketing & Ads","https://clevertap.com"],
  ["Cometly","Find","Marketing & Ads","https://cometly.com"],
  ["Constant Contact","Find","Marketing & Ads","https://constantcontact.com"],
  ["Contrast","Find","Marketing & Ads","https://contrast.co"],
  ["Convert.com (Convert Experiences)","Find","Marketing & Ads","https://convert.com"],
  ["Customer.io","Find","Marketing & Ads","https://customer.io"],
  ["Demio","Find","Marketing & Ads","https://demio.com"],
  ["DigitalPilot","Find","Marketing & Ads","https://digitalpilot.app"],
  ["Dotdigital","Find","Marketing & Ads","https://dotdigital.com"],
  ["Dynamic Yield (Mastercard)","Find","Marketing & Ads","https://dynamicyield.com"],
  ["Etropo","Find","Marketing & Ads","https://etropo.com"],
  ["Everflow","Find","Marketing & Ads","https://everflow.io"],
  ["Extole","Find","Marketing & Ads","https://extole.com"],
  ["Fibbler","Find","Marketing & Ads","https://fibbler.co"],
  ["Framer","Find","Marketing & Ads","https://framer.com"],
  ["Friendbuy","Find","Marketing & Ads","https://friendbuy.com"],
  ["GetResponse","Find","Marketing & Ads","https://getresponse.com"],
  ["Goldcast","Find","Marketing & Ads","https://goldcast.io"],
  ["Google Business Profile API","Find","Marketing & Ads","https://google.com"],
  ["GrowSurf","Find","Marketing & Ads","https://growsurf.com"],
  ["HeyStream","Find","Marketing & Ads","https://heystream.com"],
  ["Hootsuite","Find","Marketing & Ads","https://hootsuite.com"],
  ["Hubilo","Find","Marketing & Ads","https://hubilo.com"],
  ["impact.com","Find","Marketing & Ads","https://impact.com"],
  ["Inflection.io","Find","Marketing & Ads","https://inflection.io"],
  ["Influ2","Find","Marketing & Ads","https://influ2.com"],
  ["Insider One","Find","Marketing & Ads","https://insiderone.com"],
  ["Instapage","Find","Marketing & Ads","https://instapage.com"],
  ["Iterable","Find","Marketing & Ads","https://iterable.com"],
  ["Kit (formerly ConvertKit)","Find","Marketing & Ads","https://kit.com"],
  ["Klaviyo","Find","Marketing & Ads","https://klaviyo.com"],
  ["Leadjourney","Find","Marketing & Ads","https://leadjourney.io"],
  ["LinkedIn Conversions API","Find","Marketing & Ads","https://linkedin.com"],
  ["Mailchimp","Find","Marketing & Ads","https://mailchimp.com"],
  ["MailerLite","Find","Marketing & Ads","https://mailerlite.com"],
  ["Mailjet","Find","Marketing & Ads","https://mailjet.com"],
  ["Manago AI","Find","Marketing & Ads","https://manago.ai"],
  ["Mapp Cloud (Mapp Marketing Cloud / Mapp Intelligence)","Find","Marketing & Ads","https://mapp.com"],
  ["Marketo (Adobe Marketo Engage)","Find","Marketing & Ads","https://adobe.com"],
  ["Mautic","Find","Marketing & Ads","https://mautic.org"],
  ["Meltwater (via Owler/PR review monitoring)","Find","Marketing & Ads","https://meltwater.com"],
  ["Mention","Find","Marketing & Ads","https://mention.com"],
  ["Meta Conversions API","Find","Marketing & Ads","https://facebook.com"],
  ["Meta Marketing API","Find","Marketing & Ads","https://facebook.com"],
  ["Metadata.io","Find","Marketing & Ads","https://metadata.io"],
  ["MoEngage","Find","Marketing & Ads","https://moengage.com"],
  ["Monetate","Find","Marketing & Ads","https://monetate.com"],
  ["Netcore Cloud","Find","Marketing & Ads","https://netcorecloud.com"],
  ["Oktopost","Find","Marketing & Ads","https://oktopost.com"],
  ["Omniconvert","Find","Marketing & Ads","https://omniconvert.com"],
  ["Omnisend","Find","Marketing & Ads","https://omnisend.com"],
  ["Optimizely (Web/Feature Experimentation + Content Marketing Platform)","Find","Marketing & Ads","https://optimizely.com"],
  ["Oracle Eloqua","Find","Marketing & Ads","https://oracle.com"],
  ["Ortto","Find","Marketing & Ads","https://ortto.com"],
  ["Partnero","Find","Marketing & Ads","https://partnero.com"],
  ["Pinterest API","Find","Marketing & Ads","https://pinterest.com"],
  ["Post Affiliate Pro","Find","Marketing & Ads","https://postaffiliatepro.com"],
  ["Quotient","Find","Marketing & Ads","https://getquotient.ai"],
  ["Reddit Ads API","Find","Marketing & Ads","https://reddit.com"],
  ["Reditus","Find","Marketing & Ads","https://reditus.io"],
  ["Referral Factory","Find","Marketing & Ads","https://referral-factory.com"],
  ["Referral Rock","Find","Marketing & Ads","https://referralrock.com"],
  ["ReferralCandy","Find","Marketing & Ads","https://referralcandy.com"],
  ["Refersion","Find","Marketing & Ads","https://refersion.com"],
  ["Rewardful","Find","Marketing & Ads","https://rewardful.com"],
  ["Riddle","Find","Marketing & Ads","https://riddle.com"],
  ["RingCentral Events","Find","Marketing & Ads","https://ringcentral.com/rc-events"],
  ["SAP Emarsys (Emarsys / SAP Engagement Cloud)","Find","Marketing & Ads","https://emarsys.com"],
  ["Selligent by Marigold (Marigold Engage)","Find","Marketing & Ads","https://meetmarigold.com"],
  ["Sendlane","Find","Marketing & Ads","https://sendlane.com"],
  ["Senja","Find","Marketing & Ads","https://senja.io"],
  ["Sessionize","Find","Marketing & Ads","https://sessionize.com"],
  ["SiteSeam","Find","Marketing & Ads","https://siteseam.com"],
  ["SlapFive","Find","Marketing & Ads","https://slapfive.com"],
  ["Splash","Find","Marketing & Ads","https://splashthat.com"],
  ["Sprout Social","Find","Marketing & Ads","https://sproutsocial.com"],
  ["Squarespace","Find","Marketing & Ads","https://squarespace.com"],
  ["Stova (Aventri)","Find","Marketing & Ads","https://stova.io"],
  ["Surface Labs","Find","Marketing & Ads","https://withsurface.com"],
  ["Swapcard","Find","Marketing & Ads","https://swapcard.com"],
  ["Swoogo","Find","Marketing & Ads","https://swoogo.com"],
  ["Synter","Find","Marketing & Ads","https://syntermedia.ai"],
  ["Talkable","Find","Marketing & Ads","https://talkable.com"],
  ["TikTok Ads (Marketing API)","Find","Marketing & Ads","https://tiktok.com"],
  ["TikTok Lead Generation","Find","Marketing & Ads","https://tiktok.com"],
  ["Tinct","Find","Marketing & Ads","https://tinct.ai"],
  ["Tito","Find","Marketing & Ads","https://ti.to"],
  ["Tolstoy","Find","Marketing & Ads","https://gotolstoy.com"],
  ["Tolt","Find","Marketing & Ads","https://tolt.com"],
  ["Trustpilot","Find","Marketing & Ads","https://trustpilot.com"],
  ["Unbounce","Find","Marketing & Ads","https://unbounce.com"],
  ["UserEvidence","Find","Marketing & Ads","https://userevidence.com"],
  ["vFairs","Find","Marketing & Ads","https://vfairs.com"],
  ["Viral Loops","Find","Marketing & Ads","https://viral-loops.com"],
  ["Vista Social","Find","Marketing & Ads","https://vistasocial.com"],
  ["WebEngage","Find","Marketing & Ads","https://webengage.com"],
  ["Webex Events (formerly Socio)","Find","Marketing & Ads","https://webex.com"],
  ["Webflow","Find","Marketing & Ads","https://webflow.com"],
  ["Wistia","Find","Marketing & Ads","https://wistia.com"],
  ["X (Twitter) Lead Gen Ads","Find","Marketing & Ads","https://x.com"],
  ["Xink","Find","Marketing & Ads","https://xink.io"],
  ["Yotpo (Reviews & Loyalty & Referrals)","Find","Marketing & Ads","https://yotpo.com"],
  ["Zuddl","Find","Marketing & Ads","https://zuddl.com"],
  ["Amplemarket (Duo)","Find","Prospecting & Social","https://amplemarket.com"],
  ["Apollo","Find","Prospecting & Social","https://apollo.io",1],
  ["AuthoredUp","Find","Prospecting & Social","https://authoredup.com"],
  ["Bevy","Find","Prospecting & Social","https://bevy.com"],
  ["Bluesky","Find","Prospecting & Social","https://bsky.app"],
  ["Brella","Find","Prospecting & Social","https://brella.io"],
  ["Circle","Find","Prospecting & Social","https://circle.so"],
  ["Discord","Find","Prospecting & Social","https://discord.com"],
  ["Dux-Soup","Find","Prospecting & Social","https://dux-soup.com"],
  ["Hacker News API","Find","Prospecting & Social","https://ycombinator.com"],
  ["Heylo","Find","Prospecting & Social","https://heylo.com"],
  ["HeyReach","Find","Prospecting & Social","https://heyreach.io"],
  ["Influitive","Find","Prospecting & Social","https://influitive.com"],
  ["La Growth Machine","Find","Prospecting & Social","https://lagrowthmachine.com"],
  ["Lempod","Find","Prospecting & Social","https://lempod.com"],
  ["LinkedIn","Find","Prospecting & Social","https://linkedin.com",1],
  ["Luma","Find","Prospecting & Social","https://lu.ma"],
  ["Mastodon API","Find","Prospecting & Social","https://joinmastodon.org"],
  ["Meetup","Find","Prospecting & Social","https://meetup.com"],
  ["Meta / Instagram","Find","Prospecting & Social","https://meta.com"],
  ["Mighty Networks","Find","Prospecting & Social","https://mightynetworks.com"],
  ["Origami","Find","Prospecting & Social","https://origami.chat"],
  ["Overloop","Find","Prospecting & Social","https://overloop.com"],
  ["Product Hunt API","Find","Prospecting & Social","https://producthunt.com"],
  ["Reddit","Find","Prospecting & Social","https://reddit.com"],
  ["Seamless.AI","Find","Prospecting & Social","https://seamless.ai"],
  ["Sendspark","Find","Prospecting & Social","https://sendspark.com"],
  ["Snov.io","Find","Prospecting & Social","https://snov.io"],
  ["SPOTIO","Find","Prospecting & Social","https://spotio.com"],
  ["Taplio","Find","Prospecting & Social","https://taplio.com"],
  ["Threads API","Find","Prospecting & Social","https://facebook.com"],
  ["TikTok","Find","Prospecting & Social","https://tiktok.com"],
  ["Unify","Find","Prospecting & Social","https://unifygtm.com"],
  ["Vidyard","Find","Prospecting & Social","https://vidyard.com"],
  ["Waalaxy","Find","Prospecting & Social","https://waalaxy.com"],
  ["X","Find","Prospecting & Social","https://x.com"],
  ["3CX","Connect","Calling & Voice","https://3cx.com"],
  ["8x8","Connect","Calling & Voice","https://8x8.com"],
  ["Aircall","Connect","Calling & Voice","https://aircall.io"],
  ["Allo","Connect","Calling & Voice","https://withallo.com"],
  ["Aloware","Connect","Calling & Voice","https://aloware.com"],
  ["Bandwidth","Connect","Calling & Voice","https://bandwidth.com"],
  ["Blacklist Alliance","Connect","Calling & Voice","https://blacklistalliance.com"],
  ["Bland AI","Connect","Calling & Voice","https://bland.ai"],
  ["CallRail","Connect","Calling & Voice","https://callrail.com"],
  ["CloudTalk","Connect","Calling & Voice","https://cloudtalk.io"],
  ["Contact Center Compliance (DNC.com)","Connect","Calling & Voice","https://dnc.com"],
  ["CTM","Connect","Calling & Voice","https://ctm.com"],
  ["Dialfyne","Connect","Calling & Voice","https://dialfyne.com"],
  ["Dialpad","Connect","Calling & Voice","https://dialpad.com"],
  ["Exotel","Connect","Calling & Voice","https://exotel.com"],
  ["First Orion (SENTRY / INFORM Branded Calling)","Connect","Calling & Voice","https://firstorion.com"],
  ["Freshcaller","Connect","Calling & Voice","https://freshworks.com"],
  ["GoTo Connect","Connect","Calling & Voice","https://goto.com"],
  ["HighLevel Voice AI Public APIs","Connect","Calling & Voice","https://gohighlevel.com"],
  ["Hiya (Hiya Connect / Hiya for Developers)","Connect","Calling & Voice","https://hiya.com"],
  ["Infinity","Connect","Calling & Voice","https://infinity.co"],
  ["Invoca","Connect","Calling & Voice","https://invoca.com"],
  ["JustCall","Connect","Calling & Voice","https://justcall.io"],
  ["Kixie","Connect","Calling & Voice","https://kixie.com"],
  ["Knowlarity","Connect","Calling & Voice","https://knowlarity.com"],
  ["Koncert","Connect","Calling & Voice","https://koncert.com"],
  ["KrispCall","Connect","Calling & Voice","https://krispcall.com"],
  ["Marchex","Connect","Calling & Voice","https://marchex.com"],
  ["MyOperator","Connect","Calling & Voice","https://myoperator.com"],
  ["Nomorobo","Connect","Calling & Voice","https://nomorobo.com"],
  ["Ozonetel","Connect","Calling & Voice","https://ozonetel.com"],
  ["PhoneBurner","Connect","Calling & Voice","https://phoneburner.com"],
  ["Plivo","Connect","Calling & Voice","https://plivo.com"],
  ["Quo","Connect","Calling & Voice","https://quo.com"],
  ["Reached","Connect","Calling & Voice","https://reachedapp.com"],
  ["Regal.ai","Connect","Calling & Voice","https://regal.ai"],
  ["Retell AI","Connect","Calling & Voice","https://retellai.com"],
  ["Retreaver","Connect","Calling & Voice","https://retreaver.com"],
  ["Ringba","Connect","Calling & Voice","https://ringba.com"],
  ["RingCentral","Connect","Calling & Voice","https://ringcentral.com"],
  ["Ringee","Connect","Calling & Voice","https://ringee.io"],
  ["Ringover","Connect","Calling & Voice","https://ringover.com"],
  ["SignalWire","Connect","Calling & Voice","https://signalwire.com"],
  ["Synthflow AI","Connect","Calling & Voice","https://synthflow.ai"],
  ["Telnyx","Connect","Calling & Voice","https://telnyx.com"],
  ["Toky","Connect","Calling & Voice","https://toky.co"],
  ["Vapi","Connect","Calling & Voice","https://vapi.ai"],
  ["Vonage Voice API","Connect","Calling & Voice","https://vonage.com"],
  ["Voximplant","Connect","Calling & Voice","https://voximplant.com"],
  ["Ytel","Connect","Calling & Voice","https://ytel.com"],
  ["Zadarma","Connect","Calling & Voice","https://zadarma.com"],
  ["Zendesk Talk","Connect","Calling & Voice","https://zendesk.com"],
  ["AhaSend","Connect","Email & Sequencing","https://ahasend.com"],
  ["Amazon SES","Connect","Email & Sequencing","https://amazon.com"],
  ["Apple Mail / Apple Calendar (extensions & CalDAV/CardDAV)","Connect","Email & Sequencing","https://apple.com"],
  ["Autoklose","Connect","Email & Sequencing","https://autoklose.com"],
  ["Autotouch AI","Connect","Email & Sequencing","https://autotouch.ai"],
  ["AWeber","Connect","Email & Sequencing","https://aweber.com"],
  ["Brevo Transactional Email","Connect","Email & Sequencing","https://brevo.com"],
  ["Drip","Connect","Email & Sequencing","https://drip.com"],
  ["Elastic Email","Connect","Email & Sequencing","https://elasticemail.com"],
  ["Email on Acid","Connect","Email & Sequencing","https://emailonacid.com"],
  ["EmailBison","Connect","Email & Sequencing","https://emailbison.com"],
  ["Encharge","Connect","Email & Sequencing","https://encharge.io"],
  ["Exclaimer","Connect","Email & Sequencing","https://exclaimer.com"],
  ["Fastmail","Connect","Email & Sequencing","https://fastmail.com"],
  ["GlockApps","Connect","Email & Sequencing","https://glockapps.com"],
  ["Gmail","Connect","Email & Sequencing","https://google.com",1],
  ["Google Postmaster Tools","Connect","Email & Sequencing","https://google.com"],
  ["Housecat","Connect","Email & Sequencing","https://housecat.com"],
  ["Instantly","Connect","Email & Sequencing","https://instantly.ai"],
  ["Klenty","Connect","Email & Sequencing","https://klenty.com"],
  ["lemlist","Connect","Email & Sequencing","https://lemlist.com"],
  ["Listmonk","Connect","Email & Sequencing","https://listmonk.app"],
  ["Litmus","Connect","Email & Sequencing","https://litmus.com"],
  ["Loops","Connect","Email & Sequencing","https://loops.so"],
  ["Mail-Tester (mail-tester.com)","Connect","Email & Sequencing","https://mail-tester.com"],
  ["Mailchimp Transactional","Connect","Email & Sequencing","https://mailchimp.com"],
  ["Maildoso","Connect","Email & Sequencing","https://maildoso.ai"],
  ["Mailgun","Connect","Email & Sequencing","https://mailgun.com"],
  ["MailReach","Connect","Email & Sequencing","https://mailreach.co"],
  ["Mailshake","Connect","Email & Sequencing","https://mailshake.com"],
  ["Mailtrap","Connect","Email & Sequencing","https://mailtrap.io"],
  ["Missive","Connect","Email & Sequencing","https://missiveapp.com"],
  ["Mixmax","Connect","Email & Sequencing","https://mixmax.com"],
  ["Onbox","Connect","Email & Sequencing","https://onbox.ing"],
  ["Outlook","Connect","Email & Sequencing","https://microsoft.com",1],
  ["Outreach","Connect","Email & Sequencing","https://outreach.io",1],
  ["Postal","Connect","Email & Sequencing","https://postalserver.io"],
  ["Postmark","Connect","Email & Sequencing","https://postmarkapp.com"],
  ["Primeforge","Connect","Email & Sequencing","https://primeforge.ai"],
  ["QuickMail","Connect","Email & Sequencing","https://quickmail.io"],
  ["Reachinbox","Connect","Email & Sequencing","https://reachinbox.ai"],
  ["Reply.io (Jason AI / Bella)","Connect","Email & Sequencing","https://reply.io"],
  ["Resend","Connect","Email & Sequencing","https://resend.com"],
  ["Salesforge","Connect","Email & Sequencing","https://salesforge.ai"],
  ["Saleshandy","Connect","Email & Sequencing","https://saleshandy.com"],
  ["Salesloft","Connect","Email & Sequencing","https://salesloft.com",1],
  ["SendGrid","Connect","Email & Sequencing","https://sendgrid.com"],
  ["SendLayer","Connect","Email & Sequencing","https://sendlayer.com"],
  ["Slashy","Connect","Email & Sequencing","https://slashy.com"],
  ["Smartlead","Connect","Email & Sequencing","https://smartlead.ai"],
  ["SMTP2GO","Connect","Email & Sequencing","https://smtp2go.com"],
  ["SocketLabs","Connect","Email & Sequencing","https://socketlabs.com"],
  ["Thunderbird","Connect","Email & Sequencing","https://thunderbird.net"],
  ["Userlist","Connect","Email & Sequencing","https://userlist.com"],
  ["Warmbox","Connect","Email & Sequencing","https://warmbox.ai"],
  ["Woodpecker","Connect","Email & Sequencing","https://woodpecker.co"],
  ["ZeroBounce","Connect","Email & Sequencing","https://zerobounce.net"],
  ["Zimbra","Connect","Email & Sequencing","https://zimbra.com"],
  ["Zoho Mail","Connect","Email & Sequencing","https://zoho.com"],
  ["&Open","Connect","Gifting, Travel & Entertainment","https://andopen.co"],
  ["Amadeus","Connect","Gifting, Travel & Entertainment","https://amadeus.com"],
  ["Awardco","Connect","Gifting, Travel & Entertainment","https://awardco.com"],
  ["Bonusly","Connect","Gifting, Travel & Entertainment","https://bonus.ly"],
  ["Booking.com","Connect","Gifting, Travel & Entertainment","https://booking.com"],
  ["Click2Mail","Connect","Gifting, Travel & Entertainment","https://click2mail.com"],
  ["Cloudinary","Connect","Gifting, Travel & Entertainment","https://cloudinary.com"],
  ["Descript","Connect","Gifting, Travel & Entertainment","https://descript.com"],
  ["DoorDash","Connect","Gifting, Travel & Entertainment","https://doordash.com"],
  ["Duffel","Connect","Gifting, Travel & Entertainment","https://duffel.com"],
  ["Eventbrite","Connect","Gifting, Travel & Entertainment","https://eventbrite.com"],
  ["Gift Up!","Connect","Gifting, Travel & Entertainment","https://giftup.app"],
  ["Giftbit","Connect","Gifting, Travel & Entertainment","https://giftbit.com"],
  ["Giftnote","Connect","Gifting, Travel & Entertainment","https://giftnote.com"],
  ["Giftogram","Connect","Gifting, Travel & Entertainment","https://giftogram.com"],
  ["Goody","Connect","Gifting, Travel & Entertainment","https://ongoody.com"],
  ["Handwrytten","Connect","Gifting, Travel & Entertainment","https://handwrytten.com"],
  ["Instacart","Connect","Gifting, Travel & Entertainment","https://instacart.com"],
  ["Kaltura","Connect","Gifting, Travel & Entertainment","https://kaltura.com"],
  ["Kotis Design","Connect","Gifting, Travel & Entertainment","https://kotisdesign.com"],
  ["Lob","Connect","Gifting, Travel & Entertainment","https://lob.com"],
  ["Loop & Tie","Connect","Gifting, Travel & Entertainment","https://loopandtie.com"],
  ["Navan","Connect","Gifting, Travel & Entertainment","https://navan.com"],
  ["NewsAPI.org","Connect","Gifting, Travel & Entertainment","https://newsapi.org"],
  ["Newsdata.io","Connect","Gifting, Travel & Entertainment","https://newsdata.io"],
  ["OpenTable","Connect","Gifting, Travel & Entertainment","https://opentable.com"],
  ["Perk","Connect","Gifting, Travel & Entertainment","https://perk.com"],
  ["PFL","Connect","Gifting, Travel & Entertainment","https://pfl.com"],
  ["Postalytics","Connect","Gifting, Travel & Entertainment","https://postalytics.com"],
  ["PostGrid","Connect","Gifting, Travel & Entertainment","https://postgrid.com"],
  ["Prezzee","Connect","Gifting, Travel & Entertainment","https://prezzee.com"],
  ["Printfection (Swag Pro)","Connect","Gifting, Travel & Entertainment","https://printfection.com"],
  ["Riverside","Connect","Gifting, Travel & Entertainment","https://riverside.fm"],
  ["Route4Me","Connect","Gifting, Travel & Entertainment","https://route4me.com"],
  ["Scribeless","Connect","Gifting, Travel & Entertainment","https://scribeless.co"],
  ["Sendoso","Connect","Gifting, Travel & Entertainment","https://sendoso.com"],
  ["Simply Noted","Connect","Gifting, Travel & Entertainment","https://simplynoted.com"],
  ["Skyscanner","Connect","Gifting, Travel & Entertainment","https://skyscanner.net"],
  ["SoundCloud","Connect","Gifting, Travel & Entertainment","https://soundcloud.com"],
  ["Spotify","Connect","Gifting, Travel & Entertainment","https://spotify.com"],
  ["SwagUp","Connect","Gifting, Travel & Entertainment","https://swagup.com"],
  ["Tango Card (Rewards Genius / Tango API)","Connect","Gifting, Travel & Entertainment","https://tangocard.com"],
  ["Thnks","Connect","Gifting, Travel & Entertainment","https://thnks.com"],
  ["Toast","Connect","Gifting, Travel & Entertainment","https://toasttab.com"],
  ["Tremendous","Connect","Gifting, Travel & Entertainment","https://tremendous.com"],
  ["Twitch","Connect","Gifting, Travel & Entertainment","https://twitch.tv"],
  ["Uber","Connect","Gifting, Travel & Entertainment","https://uber.com"],
  ["Uber Eats","Connect","Gifting, Travel & Entertainment","https://ubereats.com"],
  ["Vimeo","Connect","Gifting, Travel & Entertainment","https://vimeo.com"],
  ["Xoxoday","Connect","Gifting, Travel & Entertainment","https://xoxoday.com"],
  ["YouTube","Connect","Gifting, Travel & Entertainment","https://youtube.com"],
  ["8x8 Meet","Connect","Meetings & Recording","https://8x8.com"],
  ["Acuity Scheduling","Connect","Meetings & Recording","https://acuityscheduling.com"],
  ["Airmeet","Connect","Meetings & Recording","https://airmeet.com"],
  ["Amie","Connect","Meetings & Recording","https://amie.so"],
  ["Attention","Connect","Meetings & Recording","https://attention.tech"],
  ["Avoma","Connect","Meetings & Recording","https://avoma.com"],
  ["BigMarker","Connect","Meetings & Recording","https://bigmarker.com"],
  ["Bluedot","Connect","Meetings & Recording","https://bluedothq.com"],
  ["Calendly","Connect","Meetings & Recording","https://calendly.com",1],
  ["Cap","Connect","Meetings & Recording","https://cap.so"],
  ["Caretta","Connect","Meetings & Recording","https://caretta.so"],
  ["Circleback","Connect","Meetings & Recording","https://circleback.ai"],
  ["Claap","Connect","Meetings & Recording","https://claap.io"],
  ["Clari Copilot (Wingman)","Connect","Meetings & Recording","https://clari.com"],
  ["ClickMeeting","Connect","Meetings & Recording","https://clickmeeting.com"],
  ["Convo","Connect","Meetings & Recording","https://itsconvo.com"],
  ["Dubber","Connect","Meetings & Recording","https://dubber.net"],
  ["Fathom","Connect","Meetings & Recording","https://fathom.video"],
  ["Fellow.app","Connect","Meetings & Recording","https://fellow.app"],
  ["Fireflies","Connect","Meetings & Recording","https://fireflies.ai",1],
  ["Gladia","Connect","Meetings & Recording","https://gladia.io"],
  ["Google Meet","Connect","Meetings & Recording","https://google.com"],
  ["GoTo Webinar","Connect","Meetings & Recording","https://goto.com"],
  ["Grain","Connect","Meetings & Recording","https://grain.com"],
  ["Granola","Connect","Meetings & Recording","https://granola.ai",1],
  ["Jiminny","Connect","Meetings & Recording","https://jiminny.com"],
  ["Livestorm","Connect","Meetings & Recording","https://livestorm.co"],
  ["Loom","Connect","Meetings & Recording","https://loom.com"],
  ["MeetGeek","Connect","Meetings & Recording","https://meetgeek.ai"],
  ["miniti","Connect","Meetings & Recording","https://miniti.app"],
  ["OnceHub","Connect","Meetings & Recording","https://oncehub.com"],
  ["Panopto","Connect","Meetings & Recording","https://panopto.com"],
  ["Read.ai","Connect","Meetings & Recording","https://read.ai"],
  ["Remo","Connect","Meetings & Recording","https://remo.co"],
  ["SavvyCal","Connect","Meetings & Recording","https://savvycal.com"],
  ["SimplyBook.me","Connect","Meetings & Recording","https://simplybook.me"],
  ["Square Appointments","Connect","Meetings & Recording","https://squareup.com"],
  ["tl;dv","Connect","Meetings & Recording","https://tldv.io"],
  ["Vexa","Connect","Meetings & Recording","https://vexa.ai"],
  ["Webex","Connect","Meetings & Recording","https://webex.com"],
  ["Zoho Meeting","Connect","Meetings & Recording","https://zoho.com"],
  ["Zoom","Connect","Meetings & Recording","https://zoom.com",1],
  ["360dialog","Connect","SMS & Messaging","https://360dialog.com"],
  ["Bandwidth CSP Campaign API","Connect","SMS & Messaging","https://bandwidth.com"],
  ["Bird (formerly MessageBird)","Connect","SMS & Messaging","https://bird.com"],
  ["Clickatell","Connect","SMS & Messaging","https://clickatell.com"],
  ["Courier","Connect","SMS & Messaging","https://courier.com"],
  ["Esendex","Connect","SMS & Messaging","https://esendex.co.uk"],
  ["Firebase Cloud Messaging","Connect","SMS & Messaging","https://google.com"],
  ["Google RCS Business Messaging (RCS for Business)","Connect","SMS & Messaging","https://google.com"],
  ["Gupshup","Connect","SMS & Messaging","https://gupshup.io"],
  ["Infobip","Connect","SMS & Messaging","https://infobip.com"],
  ["Kakao Business (KakaoTalk Channel / Kakao i Open Builder)","Connect","SMS & Messaging","https://kakao.com"],
  ["Kaleyra (Tanla)","Connect","SMS & Messaging","https://kaleyra.com"],
  ["LINE Messaging API","Connect","SMS & Messaging","https://line.biz"],
  ["MagicBell","Connect","SMS & Messaging","https://magicbell.com"],
  ["ManyChat","Connect","SMS & Messaging","https://manychat.com"],
  ["Messenger Platform","Connect","SMS & Messaging","https://facebook.com"],
  ["Mitto","Connect","SMS & Messaging","https://mitto.ch"],
  ["Novu","Connect","SMS & Messaging","https://novu.co"],
  ["OneSignal","Connect","SMS & Messaging","https://onesignal.com"],
  ["Postscript","Connect","SMS & Messaging","https://postscript.io"],
  ["Route Mobile (RML Connect)","Connect","SMS & Messaging","https://rmlconnect.net"],
  ["Salesmsg","Connect","SMS & Messaging","https://salesmessage.com"],
  ["SimpleTexting","Connect","SMS & Messaging","https://simpletexting.com"],
  ["Sinch","Connect","SMS & Messaging","https://sinch.com"],
  ["SlickText","Connect","SMS & Messaging","https://slicktext.com"],
  ["Tanla Platforms (Wisely / Single API)","Connect","SMS & Messaging","https://tanla.com"],
  ["Telegram","Connect","SMS & Messaging","https://telegram.org"],
  ["Textmagic","Connect","SMS & Messaging","https://textmagic.com"],
  ["The Campaign Registry (TCR / CSP API)","Connect","SMS & Messaging","https://campaignregistry.com"],
  ["Twilio","Connect","SMS & Messaging","https://twilio.com"],
  ["Viber Business Messages","Connect","SMS & Messaging","https://viber.com"],
  ["Volt (WhatsApp)","Connect","SMS & Messaging","https://voltchat.com"],
  ["Vonage (Messages API)","Connect","SMS & Messaging","https://vonage.com"],
  ["Wati","Connect","SMS & Messaging","https://wati.io"],
  ["WeChat Official Accounts","Connect","SMS & Messaging","https://qq.com"],
  ["WhatsApp Business Platform (Cloud API)","Connect","SMS & Messaging","https://whatsapp.com"],
  ["Zalo Official Account / ZBS","Connect","SMS & Messaging","https://zalo.me"],
  ["Clio","Sell","Contracts & Legal","https://clio.com"],
  ["Concord","Sell","Contracts & Legal","https://concord.app"],
  ["Documate (Gavel)","Sell","Contracts & Legal","https://gavel.io"],
  ["DocuSign CLM","Sell","Contracts & Legal","https://docusign.com"],
  ["Gatekeeper","Sell","Contracts & Legal","https://gatekeeperhq.com"],
  ["Ironclad","Sell","Contracts & Legal","https://ironcladapp.com"],
  ["Juro","Sell","Contracts & Legal","https://juro.com"],
  ["Oneflow","Sell","Contracts & Legal","https://oneflow.com"],
  ["PactSafe","Sell","Contracts & Legal","https://pactsafe.com"],
  ["PracticePanther","Sell","Contracts & Legal","https://practicepanther.com"],
  ["360Learning","Sell","Forecasting & Enablement","https://360learning.com"],
  ["Airstride","Sell","Forecasting & Enablement","https://airstride.ai"],
  ["CaptivateIQ","Sell","Forecasting & Enablement","https://captivateiq.com"],
  ["Channelscaler","Sell","Forecasting & Enablement","https://channelscaler.com"],
  ["Clari","Sell","Forecasting & Enablement","https://clari.com"],
  ["CompCode","Sell","Forecasting & Enablement","https://compcode.ai"],
  ["Consensus","Sell","Forecasting & Enablement","https://goconsensus.com"],
  ["Docebo","Sell","Forecasting & Enablement","https://docebo.com"],
  ["Dock","Sell","Forecasting & Enablement","https://dock.us"],
  ["Everstage","Sell","Forecasting & Enablement","https://everstage.com"],
  ["Flowla","Sell","Forecasting & Enablement","https://flowla.com"],
  ["Fullcast","Sell","Forecasting & Enablement","https://fullcast.com"],
  ["Gong","Sell","Forecasting & Enablement","https://gong.io",1],
  ["Gradient Works","Sell","Forecasting & Enablement","https://gradient.works"],
  ["HowdyGo","Sell","Forecasting & Enablement","https://howdygo.com"],
  ["Navattic","Sell","Forecasting & Enablement","https://navattic.com"],
  ["Outdoo AI","Sell","Forecasting & Enablement","https://outdoo.ai"],
  ["Qobra","Sell","Forecasting & Enablement","https://qobra.co"],
  ["QuotaPath","Sell","Forecasting & Enablement","https://quotapath.com"],
  ["Seismic","Sell","Forecasting & Enablement","https://seismic.com"],
  ["Showpad","Sell","Forecasting & Enablement","https://showpad.com"],
  ["Skylar","Sell","Forecasting & Enablement","https://getskylar.com"],
  ["Storylane","Sell","Forecasting & Enablement","https://storylane.io"],
  ["Supademo","Sell","Forecasting & Enablement","https://supademo.com"],
  ["Walnut.io","Sell","Forecasting & Enablement","https://walnut.io"],
  ["Windmill","Sell","Forecasting & Enablement","https://gowindmill.com"],
  ["Adobe Acrobat Sign","Sell","Proposals & E-Signature","https://adobe.com"],
  ["Better Proposals","Sell","Proposals & E-Signature","https://betterproposals.io"],
  ["BoldSign","Sell","Proposals & E-Signature","https://boldsign.com"],
  ["Conga Composer","Sell","Proposals & E-Signature","https://conga.com"],
  ["Docmosis","Sell","Proposals & E-Signature","https://docmosis.com"],
  ["Documint","Sell","Proposals & E-Signature","https://documint.me"],
  ["Docupilot","Sell","Proposals & E-Signature","https://docupilot.app"],
  ["DocuPotion","Sell","Proposals & E-Signature","https://docupotion.com"],
  ["DocuSign","Sell","Proposals & E-Signature","https://docusign.com",1],
  ["Dropbox Sign","Sell","Proposals & E-Signature","https://dropbox.com"],
  ["Formstack Documents","Sell","Proposals & E-Signature","https://formstack.com"],
  ["Inkit","Sell","Proposals & E-Signature","https://inkit.com"],
  ["Loopio","Sell","Proposals & E-Signature","https://loopio.com"],
  ["Nusii","Sell","Proposals & E-Signature","https://nusii.com"],
  ["OneSpan Sign","Sell","Proposals & E-Signature","https://onespan.com"],
  ["PandaDoc","Sell","Proposals & E-Signature","https://pandadoc.com"],
  ["Proposify","Sell","Proposals & E-Signature","https://proposify.com"],
  ["Qwilr","Sell","Proposals & E-Signature","https://qwilr.com"],
  ["Signeasy","Sell","Proposals & E-Signature","https://signeasy.com"],
  ["SignNow","Sell","Proposals & E-Signature","https://signnow.com"],
  ["SignRequest","Sell","Proposals & E-Signature","https://signrequest.com"],
  ["Xodo Sign","Sell","Proposals & E-Signature","https://xodosign.com"],
  ["Youtrust","Sell","Proposals & E-Signature","https://youtrust.com"],
  ["Zoho Sign","Sell","Proposals & E-Signature","https://zoho.com"],
  ["Adyen","Sell","Quoting, Billing & Payments","https://adyen.com"],
  ["Airwallex","Sell","Quoting, Billing & Payments","https://airwallex.com"],
  ["Avalara","Sell","Quoting, Billing & Payments","https://avalara.com"],
  ["Bill.com","Sell","Quoting, Billing & Payments","https://bill.com"],
  ["Bold Commerce","Sell","Quoting, Billing & Payments","https://boldcommerce.com"],
  ["Braintree","Sell","Quoting, Billing & Payments","https://braintreepayments.com"],
  ["Brex","Sell","Quoting, Billing & Payments","https://brex.com"],
  ["Capchase","Sell","Quoting, Billing & Payments","https://capchase.com"],
  ["Chargebee","Sell","Quoting, Billing & Payments","https://chargebee.com"],
  ["Chargezoom","Sell","Quoting, Billing & Payments","https://chargezoom.com"],
  ["Clazar","Sell","Quoting, Billing & Payments","https://clazar.io"],
  ["Cratejoy","Sell","Quoting, Billing & Payments","https://cratejoy.com"],
  ["DealHub","Sell","Quoting, Billing & Payments","https://dealhub.io"],
  ["Dwolla","Sell","Quoting, Billing & Payments","https://dwolla.com"],
  ["Finix","Sell","Quoting, Billing & Payments","https://finix.com"],
  ["Flywire","Sell","Quoting, Billing & Payments","https://flywire.com"],
  ["FreshBooks","Sell","Quoting, Billing & Payments","https://freshbooks.com"],
  ["GoCardless","Sell","Quoting, Billing & Payments","https://gocardless.com"],
  ["Gumroad","Sell","Quoting, Billing & Payments","https://gumroad.com"],
  ["Highnote","Sell","Quoting, Billing & Payments","https://highnote.com"],
  ["Humanitix","Sell","Quoting, Billing & Payments","https://humanitix.com"],
  ["Hyperline","Sell","Quoting, Billing & Payments","https://hyperline.co"],
  ["Increase","Sell","Quoting, Billing & Payments","https://increase.com"],
  ["Invoiced","Sell","Quoting, Billing & Payments","https://invoiced.com"],
  ["Lago","Sell","Quoting, Billing & Payments","https://getlago.com"],
  ["Lemon Squeezy","Sell","Quoting, Billing & Payments","https://lemonsqueezy.com"],
  ["Lithic","Sell","Quoting, Billing & Payments","https://lithic.com"],
  ["Maxio","Sell","Quoting, Billing & Payments","https://maxio.com"],
  ["Measure","Sell","Quoting, Billing & Payments","https://getmeasure.com"],
  ["Mercury","Sell","Quoting, Billing & Payments","https://mercury.com"],
  ["Metronome","Sell","Quoting, Billing & Payments","https://metronome.com"],
  ["Modern Treasury","Sell","Quoting, Billing & Payments","https://moderntreasury.com"],
  ["MonetizeNow","Sell","Quoting, Billing & Payments","https://monetizenow.ai"],
  ["Moov","Sell","Quoting, Billing & Payments","https://moov.io"],
  ["Nue (formerly Monetize)","Sell","Quoting, Billing & Payments","https://nue.io"],
  ["Numeral","Sell","Quoting, Billing & Payments","https://numeral.com"],
  ["Orb","Sell","Quoting, Billing & Payments","https://withorb.com"],
  ["Ordermentum","Sell","Quoting, Billing & Payments","https://ordermentum.com"],
  ["Ordway","Sell","Quoting, Billing & Payments","https://ordwaylabs.com"],
  ["Paddle","Sell","Quoting, Billing & Payments","https://paddle.com"],
  ["Paid","Sell","Quoting, Billing & Payments","https://paid.ai"],
  ["PayPal","Sell","Quoting, Billing & Payments","https://paypal.com"],
  ["Paystand","Sell","Quoting, Billing & Payments","https://paystand.com"],
  ["Quaderno","Sell","Quoting, Billing & Payments","https://quaderno.io"],
  ["Recharge","Sell","Quoting, Billing & Payments","https://getrecharge.com"],
  ["Recurly","Sell","Quoting, Billing & Payments","https://recurly.com"],
  ["Resolve","Sell","Quoting, Billing & Payments","https://resolvepay.com"],
  ["Salesbricks","Sell","Quoting, Billing & Payments","https://salesbricks.com"],
  ["Sellsy","Sell","Quoting, Billing & Payments","https://sellsy.com"],
  ["Sequence","Sell","Quoting, Billing & Payments","https://sequencehq.com"],
  ["Solvimon","Sell","Quoting, Billing & Payments","https://solvimon.com"],
  ["Sovos","Sell","Quoting, Billing & Payments","https://sovos.com"],
  ["Sphere","Sell","Quoting, Billing & Payments","https://spherepay.co"],
  ["Square","Sell","Quoting, Billing & Payments","https://squareup.com"],
  ["Stripe","Sell","Quoting, Billing & Payments","https://stripe.com"],
  ["Tabs","Sell","Quoting, Billing & Payments","https://tabs.com"],
  ["TaxJar","Sell","Quoting, Billing & Payments","https://taxjar.com"],
  ["Tipalti","Sell","Quoting, Billing & Payments","https://tipalti.com"],
  ["Turnstile","Sell","Quoting, Billing & Payments","https://turnstile.ai"],
  ["Unit","Sell","Quoting, Billing & Payments","https://unit.co"],
  ["Versapay","Sell","Quoting, Billing & Payments","https://versapay.com"],
  ["Wise","Sell","Quoting, Billing & Payments","https://wise.com"],
  ["WooCommerce","Sell","Quoting, Billing & Payments","https://woocommerce.com"],
  ["Younium","Sell","Quoting, Billing & Payments","https://younium.com"],
  ["Zoho Billing (Zoho Subscriptions)","Sell","Quoting, Billing & Payments","https://zoho.com"],
  ["Zuora","Sell","Quoting, Billing & Payments","https://zuora.com"],
  ["ABsmartly","Manage","Analytics & BI","https://absmartly.com"],
  ["Adobe Analytics","Manage","Analytics & BI","https://adobe.com"],
  ["Ahrefs","Manage","Analytics & BI","https://ahrefs.com"],
  ["Amazon Redshift","Manage","Analytics & BI","https://amazon.com"],
  ["Amplitude","Manage","Analytics & BI","https://amplitude.com"],
  ["Attribution App (Attribution.com)","Manage","Analytics & BI","https://attributionapp.com"],
  ["Azure Synapse Analytics","Manage","Analytics & BI","https://microsoft.com"],
  ["Baremetrics","Manage","Analytics & BI","https://baremetrics.com"],
  ["BuiltWith","Manage","Analytics & BI","https://builtwith.com"],
  ["ChartMogul","Manage","Analytics & BI","https://chartmogul.com"],
  ["Chattermill","Manage","Analytics & BI","https://chattermill.com"],
  ["ClickHouse","Manage","Analytics & BI","https://clickhouse.com"],
  ["Cloudflare Web Analytics","Manage","Analytics & BI","https://cloudflare.com"],
  ["Contentsquare (incl. Hotjar)","Manage","Analytics & BI","https://contentsquare.com"],
  ["Cube (Cube.dev)","Manage","Analytics & BI","https://cube.dev"],
  ["Databox","Manage","Analytics & BI","https://databox.com"],
  ["Databricks","Manage","Analytics & BI","https://databricks.com"],
  ["Datadog","Manage","Analytics & BI","https://datadoghq.com"],
  ["dbt Cloud (dbt Labs)","Manage","Analytics & BI","https://getdbt.com"],
  ["Dreamdata","Manage","Analytics & BI","https://dreamdata.io"],
  ["Embeddable","Manage","Analytics & BI","https://embeddable.com"],
  ["Explo","Manage","Analytics & BI","https://explo.co"],
  ["FullStory","Manage","Analytics & BI","https://fullstory.com"],
  ["Geckoboard","Manage","Analytics & BI","https://geckoboard.com"],
  ["GoodData","Manage","Analytics & BI","https://gooddata.com"],
  ["Google Analytics 4","Manage","Analytics & BI","https://google.com"],
  ["Google BigQuery","Manage","Analytics & BI","https://google.com"],
  ["Google Search Console","Manage","Analytics & BI","https://google.com"],
  ["Google Tag Manager","Manage","Analytics & BI","https://google.com"],
  ["Grafana","Manage","Analytics & BI","https://grafana.com"],
  ["GrowthBook","Manage","Analytics & BI","https://growthbook.io"],
  ["Heap","Manage","Analytics & BI","https://heap.io"],
  ["Hex","Manage","Analytics & BI","https://hex.tech"],
  ["HockeyStack","Manage","Analytics & BI","https://hockeystack.com"],
  ["Hyros","Manage","Analytics & BI","https://hyros.com"],
  ["Indicative","Manage","Analytics & BI","https://indicative.com"],
  ["Kameleoon","Manage","Analytics & BI","https://kameleoon.com"],
  ["Klipfolio","Manage","Analytics & BI","https://klipfolio.com"],
  ["Lightdash","Manage","Analytics & BI","https://lightdash.com"],
  ["Looker","Manage","Analytics & BI","https://looker.com"],
  ["Luzmo (Cumul.io)","Manage","Analytics & BI","https://luzmo.com"],
  ["Matomo","Manage","Analytics & BI","https://matomo.org"],
  ["Metabase","Manage","Analytics & BI","https://metabase.com"],
  ["Microsoft Clarity","Manage","Analytics & BI","https://microsoft.com"],
  ["Microsoft Fabric","Manage","Analytics & BI","https://microsoft.com"],
  ["Microsoft Power BI","Manage","Analytics & BI","https://microsoft.com"],
  ["Mixpanel","Manage","Analytics & BI","https://mixpanel.com"],
  ["Mode (ThoughtSpot Mode)","Manage","Analytics & BI","https://mode.com"],
  ["MotherDuck","Manage","Analytics & BI","https://motherduck.com"],
  ["Mouseflow","Manage","Analytics & BI","https://mouseflow.com"],
  ["Moz","Manage","Analytics & BI","https://moz.com"],
  ["Northbeam","Manage","Analytics & BI","https://northbeam.io"],
  ["Omni Analytics","Manage","Analytics & BI","https://omni.co"],
  ["Pendo","Manage","Analytics & BI","https://pendo.io"],
  ["Permute","Manage","Analytics & BI","https://permute.ai"],
  ["Pigment","Manage","Analytics & BI","https://pigment.com"],
  ["Piwik PRO","Manage","Analytics & BI","https://piwik.pro"],
  ["Plausible Analytics","Manage","Analytics & BI","https://plausible.io"],
  ["PostHog","Manage","Analytics & BI","https://posthog.com"],
  ["Productbet","Manage","Analytics & BI","https://productbet.io"],
  ["Qlik Sense (Qlik Cloud)","Manage","Analytics & BI","https://qlik.com"],
  ["Qualaroo","Manage","Analytics & BI","https://qualaroo.com"],
  ["Redash","Manage","Analytics & BI","https://redash.io"],
  ["Ruler Analytics","Manage","Analytics & BI","https://ruleranalytics.com"],
  ["SE Ranking","Manage","Analytics & BI","https://seranking.com"],
  ["Segmetrics","Manage","Analytics & BI","https://segmetrics.io"],
  ["Semrush","Manage","Analytics & BI","https://semrush.com"],
  ["Sigma Computing","Manage","Analytics & BI","https://sigmacomputing.com"],
  ["Similarweb","Manage","Analytics & BI","https://similarweb.com"],
  ["Smartlook (Splunk Digital Experience Analytics)","Manage","Analytics & BI","https://smartlook.com"],
  ["Snowplow","Manage","Analytics & BI","https://snowplow.io"],
  ["Sprig","Manage","Analytics & BI","https://sprig.com"],
  ["SpyFu","Manage","Analytics & BI","https://spyfu.com"],
  ["Statsig","Manage","Analytics & BI","https://statsig.com"],
  ["Tableau","Manage","Analytics & BI","https://tableau.com"],
  ["ThoughtSpot","Manage","Analytics & BI","https://thoughtspot.com"],
  ["Triple Whale","Manage","Analytics & BI","https://triplewhale.com"],
  ["Umami","Manage","Analytics & BI","https://umami.is"],
  ["Userpilot","Manage","Analytics & BI","https://userpilot.com"],
  ["VWO (Wingify)","Manage","Analytics & BI","https://vwo.com"],
  ["Wappalyzer","Manage","Analytics & BI","https://wappalyzer.com"],
  ["Woopra","Manage","Analytics & BI","https://woopra.com"],
  ["Air","Manage","Cloud Storage","https://air.inc"],
  ["Backblaze B2","Manage","Cloud Storage","https://backblaze.com"],
  ["Box","Manage","Cloud Storage","https://box.com"],
  ["Brandfolder","Manage","Cloud Storage","https://brandfolder.com"],
  ["Bynder","Manage","Cloud Storage","https://bynder.com"],
  ["Canto","Manage","Cloud Storage","https://canto.com"],
  ["Citrix ShareFile","Manage","Cloud Storage","https://sharefile.com"],
  ["Dropbox","Manage","Cloud Storage","https://dropbox.com"],
  ["Egnyte","Manage","Cloud Storage","https://egnyte.com"],
  ["Files.com","Manage","Cloud Storage","https://files.com"],
  ["Filestack","Manage","Cloud Storage","https://filestack.com"],
  ["Google Drive","Manage","Cloud Storage","https://google.com",1],
  ["MASV","Manage","Cloud Storage","https://massive.io"],
  ["Microsoft OneDrive","Manage","Cloud Storage","https://microsoft.com"],
  ["pCloud","Manage","Cloud Storage","https://pcloud.com"],
  ["Uploadcare","Manage","Cloud Storage","https://uploadcare.com"],
  ["Airtable","Manage","Projects, Docs & Chat","https://airtable.com"],
  ["Akiflow","Manage","Projects, Docs & Chat","https://akiflow.com"],
  ["Asana","Manage","Projects, Docs & Chat","https://asana.com"],
  ["Azure DevOps Boards","Manage","Projects, Docs & Chat","https://microsoft.com"],
  ["Backlog","Manage","Projects, Docs & Chat","https://backlog.com"],
  ["Basecamp","Manage","Projects, Docs & Chat","https://basecamp.com"],
  ["Bitbucket","Manage","Projects, Docs & Chat","https://bitbucket.org"],
  ["BookStack","Manage","Projects, Docs & Chat","https://bookstackapp.com"],
  ["Carbone","Manage","Projects, Docs & Chat","https://carbone.io"],
  ["Cisco Webex Messaging","Manage","Projects, Docs & Chat","https://webex.com"],
  ["ClickUp","Manage","Projects, Docs & Chat","https://clickup.com"],
  ["Confluence","Manage","Projects, Docs & Chat","https://atlassian.com"],
  ["Craft","Manage","Projects, Docs & Chat","https://craft.do"],
  ["DingTalk (钉钉)","Manage","Projects, Docs & Chat","https://dingtalk.com"],
  ["Docmost","Manage","Projects, Docs & Chat","https://docmost.com"],
  ["Document360","Manage","Projects, Docs & Chat","https://document360.com"],
  ["Dropbox Paper","Manage","Projects, Docs & Chat","https://dropbox.com"],
  ["Element (Matrix)","Manage","Projects, Docs & Chat","https://element.io"],
  ["Favro","Manage","Projects, Docs & Chat","https://favro.com"],
  ["Figma","Manage","Projects, Docs & Chat","https://figma.com"],
  ["Filestage","Manage","Projects, Docs & Chat","https://filestage.io"],
  ["Flock","Manage","Projects, Docs & Chat","https://flock.com"],
  ["Flowlu","Manage","Projects, Docs & Chat","https://flowlu.com"],
  ["Frame.io","Manage","Projects, Docs & Chat","https://frame.io"],
  ["GitBook","Manage","Projects, Docs & Chat","https://gitbook.com"],
  ["GitHub","Manage","Projects, Docs & Chat","https://github.com"],
  ["GitLab","Manage","Projects, Docs & Chat","https://gitlab.com"],
  ["Google","Manage","Projects, Docs & Chat","https://google.com"],
  ["Google Sheets","Manage","Projects, Docs & Chat","https://google.com"],
  ["Google Workspace","Manage","Projects, Docs & Chat","https://google.com"],
  ["Guru","Manage","Projects, Docs & Chat","https://getguru.com"],
  ["Hive","Manage","Projects, Docs & Chat","https://hive.com"],
  ["Huly","Manage","Projects, Docs & Chat","https://huly.io"],
  ["Jira","Manage","Projects, Docs & Chat","https://atlassian.com"],
  ["Kintone (Cybozu)","Manage","Projects, Docs & Chat","https://cybozu.com"],
  ["Lark / Feishu","Manage","Projects, Docs & Chat","https://larksuite.com"],
  ["LINE WORKS","Manage","Projects, Docs & Chat","https://line-works.com"],
  ["Linear","Manage","Projects, Docs & Chat","https://linear.app"],
  ["Lucid Suite (Lucidchart / Lucidspark)","Manage","Projects, Docs & Chat","https://lucid.co"],
  ["Mattermost","Manage","Projects, Docs & Chat","https://mattermost.com"],
  ["Microsoft","Manage","Projects, Docs & Chat","https://microsoft.com"],
  ["Microsoft 365","Manage","Projects, Docs & Chat","https://microsoft.com"],
  ["Microsoft Graph Teams Messaging & Change Notifications","Manage","Projects, Docs & Chat","https://microsoft.com"],
  ["Microsoft Teams","Manage","Projects, Docs & Chat","https://microsoft.com",1],
  ["Miro","Manage","Projects, Docs & Chat","https://miro.com"],
  ["monday.com","Manage","Projects, Docs & Chat","https://monday.com"],
  ["Morgen","Manage","Projects, Docs & Chat","https://morgen.so"],
  ["Motion","Manage","Projects, Docs & Chat","https://usemotion.com"],
  ["Mural","Manage","Projects, Docs & Chat","https://mural.co"],
  ["Notion","Manage","Projects, Docs & Chat","https://notion.com",1],
  ["Nuclino","Manage","Projects, Docs & Chat","https://nuclino.com"],
  ["OpenProject","Manage","Projects, Docs & Chat","https://openproject.org"],
  ["Outline","Manage","Projects, Docs & Chat","https://getoutline.com"],
  ["Paymo","Manage","Projects, Docs & Chat","https://paymoapp.com"],
  ["Plane","Manage","Projects, Docs & Chat","https://plane.so"],
  ["Procore","Manage","Projects, Docs & Chat","https://procore.com"],
  ["Productboard","Manage","Projects, Docs & Chat","https://productboard.com"],
  ["Pumble","Manage","Projects, Docs & Chat","https://pumble.com"],
  ["ReadMe","Manage","Projects, Docs & Chat","https://readme.com"],
  ["Redmine","Manage","Projects, Docs & Chat","https://redmine.org"],
  ["Rocket.Chat","Manage","Projects, Docs & Chat","https://rocket.chat"],
  ["Rocketlane","Manage","Projects, Docs & Chat","https://rocketlane.com"],
  ["Ryver","Manage","Projects, Docs & Chat","https://ryver.com"],
  ["Shortcut","Manage","Projects, Docs & Chat","https://shortcut.com"],
  ["Slab","Manage","Projects, Docs & Chat","https://slab.com"],
  ["Slack","Manage","Projects, Docs & Chat","https://slack.com",1],
  ["Slite","Manage","Projects, Docs & Chat","https://slite.com"],
  ["Smartsheet","Manage","Projects, Docs & Chat","https://smartsheet.com"],
  ["Sunsama","Manage","Projects, Docs & Chat","https://sunsama.com"],
  ["Superhuman Docs","Manage","Projects, Docs & Chat","https://superhuman.com"],
  ["Taiga","Manage","Projects, Docs & Chat","https://taiga.io"],
  ["Teamwork.com","Manage","Projects, Docs & Chat","https://teamwork.com"],
  ["Templafy","Manage","Projects, Docs & Chat","https://templafy.com"],
  ["Tettra","Manage","Projects, Docs & Chat","https://tettra.com"],
  ["Todoist","Manage","Projects, Docs & Chat","https://todoist.com"],
  ["Trello","Manage","Projects, Docs & Chat","https://trello.com"],
  ["Twist","Manage","Projects, Docs & Chat","https://twist.com"],
  ["WeCom (WeChat Work / 企业微信)","Manage","Projects, Docs & Chat","https://qq.com"],
  ["Wiki.js","Manage","Projects, Docs & Chat","https://js.wiki"],
  ["Wrike","Manage","Projects, Docs & Chat","https://wrike.com"],
  ["YouTrack","Manage","Projects, Docs & Chat","https://jetbrains.com"],
  ["Zoho Cliq","Manage","Projects, Docs & Chat","https://zoho.com"],
  ["Zoho Projects","Manage","Projects, Docs & Chat","https://zoho.com"],
  ["Zulip","Manage","Projects, Docs & Chat","https://zulip.com"],
  ["Alchemer (formerly SurveyGizmo)","Manage","Support & Success","https://alchemer.com"],
  ["Amazon Connect","Manage","Support & Success","https://amazon.com"],
  ["Appcues","Manage","Support & Success","https://appcues.com"],
  ["AskNicely","Manage","Support & Success","https://asknicely.com"],
  ["Atlassian Statuspage","Manage","Support & Success","https://atlassian.com"],
  ["Avaya Experience Platform","Manage","Support & Success","https://avaya.com"],
  ["BubblaV","Manage","Support & Success","https://bubblav.com"],
  ["Cachet","Manage","Support & Success","https://cachethq.io"],
  ["Canny","Manage","Support & Success","https://canny.io"],
  ["Catalyst","Manage","Support & Success","https://getcatalyst.io"],
  ["Chameleon","Manage","Support & Success","https://trychameleon.com"],
  ["Chatwoot","Manage","Support & Success","https://chatwoot.com"],
  ["Churnkey","Manage","Support & Success","https://churnkey.co"],
  ["ChurnZero","Manage","Support & Success","https://churnzero.com"],
  ["ClientSuccess","Manage","Support & Success","https://clientsuccess.com"],
  ["Crisp","Manage","Support & Success","https://crisp.chat"],
  ["Custify","Manage","Support & Success","https://custify.com"],
  ["Deskpro","Manage","Support & Success","https://deskpro.com"],
  ["Dixa","Manage","Support & Success","https://dixa.com"],
  ["Enchant","Manage","Support & Success","https://enchant.com"],
  ["Featurebase","Manage","Support & Success","https://featurebase.app"],
  ["Fider","Manage","Support & Success","https://fider.io"],
  ["Fin","Manage","Support & Success","https://fin.ai"],
  ["First Distro","Manage","Support & Success","https://firstdistro.com"],
  ["Formbricks","Manage","Support & Success","https://formbricks.com"],
  ["Forwrd.ai (now Pendo Predict)","Manage","Support & Success","https://forwrd.ai"],
  ["Freshchat (Freshworks)","Manage","Support & Success","https://freshworks.com"],
  ["Freshdesk","Manage","Support & Success","https://freshworks.com"],
  ["Front","Manage","Support & Success","https://front.com"],
  ["FunnelStory","Manage","Support & Success","https://funnelstory.ai"],
  ["Gainsight","Manage","Support & Success","https://gainsight.com"],
  ["Genesys Cloud CX","Manage","Support & Success","https://genesys.com"],
  ["GetFeedback (by SurveyMonkey)","Manage","Support & Success","https://getfeedback.com"],
  ["Gladly","Manage","Support & Success","https://gladly.com"],
  ["Gorgias","Manage","Support & Success","https://gorgias.com"],
  ["GuideCX","Manage","Support & Success","https://guidecx.com"],
  ["HappyFox","Manage","Support & Success","https://happyfox.com"],
  ["Help Scout","Manage","Support & Success","https://helpscout.com"],
  ["HelpDocs","Manage","Support & Success","https://helpdocs.io"],
  ["Helply","Manage","Support & Success","https://helply.com"],
  ["Intercom","Manage","Support & Success","https://intercom.com"],
  ["Jira Service Management","Manage","Support & Success","https://atlassian.com"],
  ["Kayako","Manage","Support & Success","https://kayako.com"],
  ["Kustomer","Manage","Support & Success","https://kustomer.com"],
  ["LiveAgent","Manage","Support & Success","https://liveagent.com"],
  ["LiveChat (Text.com)","Manage","Support & Success","https://livechat.com"],
  ["Mavenoid","Manage","Support & Success","https://mavenoid.com"],
  ["NICE CXone","Manage","Support & Success","https://nice.com"],
  ["Nicereply","Manage","Support & Success","https://nicereply.com"],
  ["Odie","Manage","Support & Success","https://heyodie.ai"],
  ["Onboard.io","Manage","Support & Success","https://onboard.io"],
  ["Phano","Manage","Support & Success","https://phano.ai"],
  ["Plain","Manage","Support & Success","https://plain.com"],
  ["Planhat","Manage","Support & Success","https://planhat.com"],
  ["Product Fruits","Manage","Support & Success","https://productfruits.com"],
  ["Productlane","Manage","Support & Success","https://productlane.com"],
  ["Pylon","Manage","Support & Success","https://usepylon.com"],
  ["Re:amaze","Manage","Support & Success","https://reamaze.com"],
  ["Refiner","Manage","Support & Success","https://refiner.io"],
  ["Retently","Manage","Support & Success","https://retently.com"],
  ["ServiceNow Customer Service Management","Manage","Support & Success","https://servicenow.com"],
  ["SparrowDesk","Manage","Support & Success","https://sparrowdesk.com"],
  ["Sprinklr","Manage","Support & Success","https://sprinklr.com"],
  ["Staircase AI","Manage","Support & Success","https://staircase.ai"],
  ["Startquestion","Manage","Support & Success","https://startquestion.com"],
  ["SurveyMonkey","Manage","Support & Success","https://surveymonkey.com"],
  ["SurveySparrow","Manage","Support & Success","https://surveysparrow.com"],
  ["Survicate","Manage","Support & Success","https://survicate.com"],
  ["Talkdesk","Manage","Support & Success","https://talkdesk.com"],
  ["tawk.to","Manage","Support & Success","https://tawk.to"],
  ["TeamSupport","Manage","Support & Success","https://teamsupport.com"],
  ["Thena","Manage","Support & Success","https://thena.ai"],
  ["Tidio","Manage","Support & Success","https://tidio.com"],
  ["Trengo","Manage","Support & Success","https://trengo.com"],
  ["Ujet","Manage","Support & Success","https://ujet.cx"],
  ["Unthread","Manage","Support & Success","https://unthread.io"],
  ["Userflow","Manage","Support & Success","https://userflow.com"],
  ["UserGuiding","Manage","Support & Success","https://userguiding.com"],
  ["Userlane","Manage","Support & Success","https://userlane.com"],
  ["Vitally","Manage","Support & Success","https://vitally.io"],
  ["Vivantio","Manage","Support & Success","https://vivantio.com"],
  ["Webex Contact Center","Manage","Support & Success","https://webex.com"],
  ["Wootric (InMoment CX)","Manage","Support & Success","https://wootric.com"],
  ["Zammad","Manage","Support & Success","https://zammad.org"],
  ["Zendesk","Manage","Support & Success","https://zendesk.com"],
  ["Zendesk Guide","Manage","Support & Success","https://zendesk.com"],
  ["Zendesk Messaging (Sunshine Conversations)","Manage","Support & Success","https://zendesk.com"],
  ["Zoho Desk","Manage","Support & Success","https://zoho.com"],
  ["Zonka Feedback","Manage","Support & Success","https://zonkafeedback.com"],
  ["Agno","Foundation","AI & Agents","https://agno.com"],
  ["Anthropic","Foundation","AI & Agents","https://anthropic.com"],
  ["AssemblyAI","Foundation","AI & Agents","https://assemblyai.com"],
  ["Base44","Foundation","AI & Agents","https://base44.com"],
  ["Baseten","Foundation","AI & Agents","https://baseten.co"],
  ["Botpress","Foundation","AI & Agents","https://botpress.com"],
  ["Braintrust","Foundation","AI & Agents","https://braintrust.dev"],
  ["Budibase","Foundation","AI & Agents","https://budibase.com"],
  ["Cartesia","Foundation","AI & Agents","https://cartesia.ai"],
  ["Chatbase","Foundation","AI & Agents","https://chatbase.co"],
  ["ChatGPT","Foundation","AI & Agents","https://chatgpt.com"],
  ["Claude","Foundation","AI & Agents","https://claude.ai"],
  ["Cognigy (NiCE)","Foundation","AI & Agents","https://cognigy.com"],
  ["Cohere","Foundation","AI & Agents","https://cohere.com"],
  ["Conversica","Foundation","AI & Agents","https://conversica.com"],
  ["Copy.ai (GTM AI)","Foundation","AI & Agents","https://copy.ai"],
  ["Cotera Pre Meeting Research","Foundation","AI & Agents","https://cotera.co"],
  ["DeepSeek","Foundation","AI & Agents","https://deepseek.com"],
  ["Dust","Foundation","AI & Agents","https://dust.tt"],
  ["ElevenLabs","Foundation","AI & Agents","https://elevenlabs.io"],
  ["Endgame","Foundation","AI & Agents","https://endgame.io"],
  ["Feathery","Foundation","AI & Agents","https://feathery.io"],
  ["Fireworks AI","Foundation","AI & Agents","https://fireworks.ai"],
  ["FolioReady","Foundation","AI & Agents","https://folioready.com"],
  ["Glean","Foundation","AI & Agents","https://glean.com"],
  ["Google Gemini","Foundation","AI & Agents","https://google.com"],
  ["Grammarly","Foundation","AI & Agents","https://grammarly.com"],
  ["Groq","Foundation","AI & Agents","https://groq.com"],
  ["Helicone","Foundation","AI & Agents","https://helicone.ai"],
  ["Helios","Foundation","AI & Agents","https://heliosapp.com"],
  ["HeyGen","Foundation","AI & Agents","https://heygen.com"],
  ["Hugging Face","Foundation","AI & Agents","https://huggingface.co"],
  ["Hume AI (EVI)","Foundation","AI & Agents","https://hume.ai"],
  ["Landbot","Foundation","AI & Agents","https://landbot.io"],
  ["Mistral","Foundation","AI & Agents","https://mistral.ai"],
  ["Modal","Foundation","AI & Agents","https://modal.com"],
  ["Obvious","Foundation","AI & Agents","https://obvious.ai"],
  ["Octave","Foundation","AI & Agents","https://octavehq.com"],
  ["OneCLI","Foundation","AI & Agents","https://onecli.sh"],
  ["OpenAI","Foundation","AI & Agents","https://openai.com"],
  ["Parsley","Foundation","AI & Agents","https://parsley.id"],
  ["Perplexity","Foundation","AI & Agents","https://perplexity.ai"],
  ["Pinecone","Foundation","AI & Agents","https://pinecone.io"],
  ["Podium","Foundation","AI & Agents","https://podium.com"],
  ["Portkey","Foundation","AI & Agents","https://portkey.ai"],
  ["Qdrant","Foundation","AI & Agents","https://qdrant.tech"],
  ["Qualified (Piper / PiperX)","Foundation","AI & Agents","https://qualified.com"],
  ["Relevance AI (Bosh)","Foundation","AI & Agents","https://relevanceai.com"],
  ["Replicate","Foundation","AI & Agents","https://replicate.com"],
  ["Revo","Foundation","AI & Agents","https://revo.ai"],
  ["Rime","Foundation","AI & Agents","https://rime.ai"],
  ["Rox","Foundation","AI & Agents","https://rox.com"],
  ["Scout","Foundation","AI & Agents","https://scoutos.com"],
  ["Smallest.ai","Foundation","AI & Agents","https://smallest.ai"],
  ["Soniox","Foundation","AI & Agents","https://soniox.com"],
  ["Stack AI","Foundation","AI & Agents","https://stackai.com"],
  ["Stilla","Foundation","AI & Agents","https://stilla.ai"],
  ["Stimulir","Foundation","AI & Agents","https://stimulir.com"],
  ["Sybill","Foundation","AI & Agents","https://sybill.ai"],
  ["Synthesia","Foundation","AI & Agents","https://synthesia.io"],
  ["Tavus","Foundation","AI & Agents","https://tavus.io"],
  ["Telnyx Voice AI Agents","Foundation","AI & Agents","https://telnyx.com"],
  ["Thoughtly","Foundation","AI & Agents","https://thoughtly.com"],
  ["Together AI","Foundation","AI & Agents","https://together.ai"],
  ["Turbopuffer","Foundation","AI & Agents","https://turbopuffer.com"],
  ["Ultravox AI","Foundation","AI & Agents","https://ultravox.ai"],
  ["Vellum","Foundation","AI & Agents","https://vellum.ai"],
  ["Voiceflow","Foundation","AI & Agents","https://voiceflow.com"],
  ["Voyage AI","Foundation","AI & Agents","https://voyageai.com"],
  ["Weaviate","Foundation","AI & Agents","https://weaviate.io"],
  ["xAI","Foundation","AI & Agents","https://x.ai"],
  ["Yellow.ai","Foundation","AI & Agents","https://yellow.ai"],
  ["ZoomInfo GTM Workspace AI Agents","Foundation","AI & Agents","https://zoominfo.com"],
  ["100ms","Foundation","Automation & Workflows","https://100ms.live"],
  ["Ably","Foundation","Automation & Workflows","https://ably.com"],
  ["Agora.io","Foundation","Automation & Workflows","https://agora.io"],
  ["Amazon Chime SDK","Foundation","Automation & Workflows","https://amazon.com"],
  ["api.video","Foundation","Automation & Workflows","https://api.video"],
  ["Appsmith","Foundation","Automation & Workflows","https://appsmith.com"],
  ["Atlassian Marketplace","Foundation","Automation & Workflows","https://atlassian.com"],
  ["Better Stack (Uptime)","Foundation","Automation & Workflows","https://betterstack.com"],
  ["BigBlueButton","Foundation","Automation & Workflows","https://bigbluebutton.org"],
  ["Chrome Web Store (extension platform)","Foundation","Automation & Workflows","https://google.com"],
  ["Cloudflare","Foundation","Automation & Workflows","https://cloudflare.com"],
  ["Cloudflare Stream","Foundation","Automation & Workflows","https://cloudflare.com"],
  ["Daily.co","Foundation","Automation & Workflows","https://daily.co"],
  ["Deepgram","Foundation","Automation & Workflows","https://deepgram.com"],
  ["Dyte","Foundation","Automation & Workflows","https://dyte.io"],
  ["Flagsmith","Foundation","Automation & Workflows","https://flagsmith.com"],
  ["Glide","Foundation","Automation & Workflows","https://glideapps.com"],
  ["Google Play Console","Foundation","Automation & Workflows","https://android.com"],
  ["incident.io","Foundation","Automation & Workflows","https://incident.io"],
  ["Instatus","Foundation","Automation & Workflows","https://instatus.com"],
  ["Jet Admin","Foundation","Automation & Workflows","https://jetadmin.io"],
  ["Jitsi","Foundation","Automation & Workflows","https://jitsi.org"],
  ["LaunchDarkly","Foundation","Automation & Workflows","https://launchdarkly.com"],
  ["LiveKit","Foundation","Automation & Workflows","https://livekit.io"],
  ["Mux","Foundation","Automation & Workflows","https://mux.com"],
  ["Neon","Foundation","Automation & Workflows","https://neon.tech"],
  ["Netlify","Foundation","Automation & Workflows","https://netlify.com"],
  ["PagerDuty","Foundation","Automation & Workflows","https://pagerduty.com"],
  ["Pexip","Foundation","Automation & Workflows","https://pexip.com"],
  ["Pipecat (Daily)","Foundation","Automation & Workflows","https://pipecat.ai"],
  ["Pusher Channels","Foundation","Automation & Workflows","https://pusher.com"],
  ["Raycast","Foundation","Automation & Workflows","https://raycast.com"],
  ["Retool","Foundation","Automation & Workflows","https://retool.com"],
  ["Rev (Rev.ai)","Foundation","Automation & Workflows","https://rev.ai"],
  ["SawStream","Foundation","Automation & Workflows","https://sawstream.com"],
  ["Sentry","Foundation","Automation & Workflows","https://sentry.io"],
  ["Sequin","Foundation","Automation & Workflows","https://sequinstream.com"],
  ["Shopify App Store / Partner API","Foundation","Automation & Workflows","https://shopify.com"],
  ["Split (Harness Feature Management & Experimentation)","Foundation","Automation & Workflows","https://split.io"],
  ["Stacker","Foundation","Automation & Workflows","https://stackerhq.com"],
  ["Supabase","Foundation","Automation & Workflows","https://supabase.com"],
  ["Vercel","Foundation","Automation & Workflows","https://vercel.com"],
  ["Vonage Video API (OpenTok)","Foundation","Automation & Workflows","https://vonage.com"],
  ["Whereby","Foundation","Automation & Workflows","https://whereby.com"],
  ["Act!","Foundation","CRM & Data Quality","https://act.com"],
  ["Affinity","Foundation","CRM & Data Quality","https://affinity.co"],
  ["Agendor","Foundation","CRM & Data Quality","https://agendor.com.br"],
  ["Agile CRM","Foundation","CRM & Data Quality","https://agilecrm.com"],
  ["Apptivo","Foundation","CRM & Data Quality","https://apptivo.com"],
  ["Attio","Foundation","CRM & Data Quality","https://attio.com",1],
  ["AWS Partner Central / ACE (Alliance/Co-sell Engagements)","Foundation","CRM & Data Quality","https://awspartner.com"],
  ["Bigin by Zoho","Foundation","CRM & Data Quality","https://bigin.com"],
  ["Bitrix24","Foundation","CRM & Data Quality","https://bitrix24.com"],
  ["Blackbaud Raiser's Edge NXT","Foundation","CRM & Data Quality","https://blackbaud.com"],
  ["Bloomerang","Foundation","CRM & Data Quality","https://bloomerang.com"],
  ["Capsule CRM","Foundation","CRM & Data Quality","https://capsulecrm.com"],
  ["Cirrus Insight","Foundation","CRM & Data Quality","https://cirrusinsight.com"],
  ["Clarify","Foundation","CRM & Data Quality","https://clarify.ai"],
  ["Clientify","Foundation","CRM & Data Quality","https://clientify.com"],
  ["Close","Foundation","CRM & Data Quality","https://close.com"],
  ["Coevera","Foundation","CRM & Data Quality","https://coevera.com"],
  ["Copper","Foundation","CRM & Data Quality","https://copper.com"],
  ["Creatio","Foundation","CRM & Data Quality","https://creatio.com"],
  ["Day.ai","Foundation","CRM & Data Quality","https://day.ai"],
  ["Daylite","Foundation","CRM & Data Quality","https://daylite.app"],
  ["Dynamics 365 / Dataverse Webhooks","Foundation","CRM & Data Quality","https://microsoft.com"],
  ["Efficy CRM","Foundation","CRM & Data Quality","https://efficy.com"],
  ["EngageBay","Foundation","CRM & Data Quality","https://engagebay.com"],
  ["EspoCRM","Foundation","CRM & Data Quality","https://espocrm.com"],
  ["Experian Data Quality (Aperture / EDQ)","Foundation","CRM & Data Quality","https://experian.com"],
  ["folk","Foundation","CRM & Data Quality","https://folk.app"],
  ["Freshsales (Freshworks CRM)","Foundation","CRM & Data Quality","https://freshworks.com"],
  ["HoneyBook","Foundation","CRM & Data Quality","https://honeybook.com"],
  ["HubSpot","Foundation","CRM & Data Quality","https://hubspot.com",1],
  ["Informatica Data Quality","Foundation","CRM & Data Quality","https://informatica.com"],
  ["Insightly","Foundation","CRM & Data Quality","https://insightly.com"],
  ["Journeybee","Foundation","CRM & Data Quality","https://journeybee.io"],
  ["Keap","Foundation","CRM & Data Quality","https://keap.com"],
  ["Kickbox","Foundation","CRM & Data Quality","https://kickbox.com"],
  ["Kiflo","Foundation","CRM & Data Quality","https://kiflo.com"],
  ["Kommo (formerly amoCRM)","Foundation","CRM & Data Quality","https://kommo.com"],
  ["LeadSquared","Foundation","CRM & Data Quality","https://leadsquared.com"],
  ["Less Annoying CRM","Foundation","CRM & Data Quality","https://lessannoyingcrm.com"],
  ["Lime CRM","Foundation","CRM & Data Quality","https://lime-technologies.com"],
  ["Magentrix","Foundation","CRM & Data Quality","https://magentrix.com"],
  ["Maximizer CRM","Foundation","CRM & Data Quality","https://maximizer.com"],
  ["Membrain","Foundation","CRM & Data Quality","https://membrain.com"],
  ["monday CRM","Foundation","CRM & Data Quality","https://monday.com"],
  ["NetHunt CRM","Foundation","CRM & Data Quality","https://nethunt.com"],
  ["Nimble CRM","Foundation","CRM & Data Quality","https://nimble.com"],
  ["noCRM.io","Foundation","CRM & Data Quality","https://nocrm.io"],
  ["Nutshell","Foundation","CRM & Data Quality","https://nutshell.com"],
  ["Odoo CRM","Foundation","CRM & Data Quality","https://odoo.com"],
  ["OnePageCRM","Foundation","CRM & Data Quality","https://onepagecrm.com"],
  ["Oracle CX Sales","Foundation","CRM & Data Quality","https://oracle.com"],
  ["PartnerPortal.io","Foundation","CRM & Data Quality","https://partnerportal.io"],
  ["PartnerStack","Foundation","CRM & Data Quality","https://partnerstack.com"],
  ["Pipedrive","Foundation","CRM & Data Quality","https://pipedrive.com"],
  ["Pipeline CRM","Foundation","CRM & Data Quality","https://pipelinecrm.com"],
  ["Ploomes","Foundation","CRM & Data Quality","https://ploomes.com"],
  ["RD Station CRM","Foundation","CRM & Data Quality","https://rdstation.com"],
  ["RingLead (ZoomInfo Operations / DaaS Suite)","Foundation","CRM & Data Quality","https://zoominfo.com"],
  ["Salesflare","Foundation","CRM & Data Quality","https://salesflare.com"],
  ["Salesforce","Foundation","CRM & Data Quality","https://salesforce.com",1],
  ["Salesmate","Foundation","CRM & Data Quality","https://salesmate.io"],
  ["Spotler CRM (Really Simple Systems)","Foundation","CRM & Data Quality","https://spotler.com"],
  ["Streak","Foundation","CRM & Data Quality","https://streak.com"],
  ["SugarCRM","Foundation","CRM & Data Quality","https://sugarcrm.com"],
  ["SuiteCRM","Foundation","CRM & Data Quality","https://suitecrm.com"],
  ["SuperOffice","Foundation","CRM & Data Quality","https://superoffice.com"],
  ["Sweep","Foundation","CRM & Data Quality","https://sweep.io"],
  ["Twenty","Foundation","CRM & Data Quality","https://twenty.com"],
  ["Upsales","Foundation","CRM & Data Quality","https://upsales.com"],
  ["Vtiger CRM","Foundation","CRM & Data Quality","https://vtiger.com"],
  ["Wealthbox","Foundation","CRM & Data Quality","https://wealthbox.com"],
  ["Workbooks CRM","Foundation","CRM & Data Quality","https://workbooks.com"],
  ["Zendesk Sell","Foundation","CRM & Data Quality","https://zendesk.com"],
  ["ZINFI","Foundation","CRM & Data Quality","https://zinfi.com"],
  ["Zoho CRM","Foundation","CRM & Data Quality","https://zoho.com"],
  ["Adobe Commerce (Magento)","Foundation","Ecommerce & Industry Systems","https://adobe.com"],
  ["Alibaba.com","Foundation","Ecommerce & Industry Systems","https://alibaba.com"],
  ["Amazon Business","Foundation","Ecommerce & Industry Systems","https://amazon.com"],
  ["Amazon SP-API","Foundation","Ecommerce & Industry Systems","https://amazon.com"],
  ["Anaplan","Foundation","Ecommerce & Industry Systems","https://anaplan.com"],
  ["Ankorstore","Foundation","Ecommerce & Industry Systems","https://ankorstore.com"],
  ["AppFolio","Foundation","Ecommerce & Industry Systems","https://appfolio.com"],
  ["Ashby (Job Board API)","Foundation","Ecommerce & Industry Systems","https://ashbyhq.com"],
  ["Axonaut","Foundation","Ecommerce & Industry Systems","https://axonaut.com"],
  ["BigCommerce","Foundation","Ecommerce & Industry Systems","https://bigcommerce.com"],
  ["Buildium","Foundation","Ecommerce & Industry Systems","https://buildium.com"],
  ["commercetools","Foundation","Ecommerce & Industry Systems","https://commercetools.com"],
  ["Coupa","Foundation","Ecommerce & Industry Systems","https://coupa.com"],
  ["CS-Cart","Foundation","Ecommerce & Industry Systems","https://cs-cart.com"],
  ["eBay","Foundation","Ecommerce & Industry Systems","https://ebay.com"],
  ["Ecwid by Lightspeed","Foundation","Ecommerce & Industry Systems","https://ecwid.com"],
  ["Elastic Path","Foundation","Ecommerce & Industry Systems","https://elasticpath.com"],
  ["Etsy","Foundation","Ecommerce & Industry Systems","https://etsy.com"],
  ["Expensify","Foundation","Ecommerce & Industry Systems","https://expensify.com"],
  ["Fourthwall","Foundation","Ecommerce & Industry Systems","https://fourthwall.com"],
  ["Greenhouse (Job Board API)","Foundation","Ecommerce & Industry Systems","https://greenhouse.io"],
  ["Guidewire InsuranceSuite (PolicyCenter/ClaimCenter/BillingCenter)","Foundation","Ecommerce & Industry Systems","https://guidewire.com"],
  ["HCL Commerce","Foundation","Ecommerce & Industry Systems","https://hcl-software.com"],
  ["Housecall Pro","Foundation","Ecommerce & Industry Systems","https://housecallpro.com"],
  ["Jaggaer","Foundation","Ecommerce & Industry Systems","https://jaggaer.com"],
  ["Jobber","Foundation","Ecommerce & Industry Systems","https://getjobber.com"],
  ["Lever (Postings API)","Foundation","Ecommerce & Industry Systems","https://lever.co"],
  ["Medusa","Foundation","Ecommerce & Industry Systems","https://medusajs.com"],
  ["Mercado Libre (Mercado Livre) API","Foundation","Ecommerce & Industry Systems","https://mercadolibre.com"],
  ["Mindbody","Foundation","Ecommerce & Industry Systems","https://mindbodyonline.com"],
  ["Mirakl","Foundation","Ecommerce & Industry Systems","https://mirakl.com"],
  ["Noloco","Foundation","Ecommerce & Industry Systems","https://noloco.io"],
  ["OpenGov","Foundation","Ecommerce & Industry Systems","https://opengov.com"],
  ["Oracle Commerce Cloud","Foundation","Ecommerce & Industry Systems","https://oracle.com"],
  ["OroCommerce","Foundation","Ecommerce & Industry Systems","https://oroinc.com"],
  ["Planful","Foundation","Ecommerce & Industry Systems","https://planful.com"],
  ["PrestaShop","Foundation","Ecommerce & Industry Systems","https://prestashop.com"],
  ["Procurify","Foundation","Ecommerce & Industry Systems","https://procurify.com"],
  ["Ramp","Foundation","Ecommerce & Industry Systems","https://ramp.com"],
  ["Ramp Procurement","Foundation","Ecommerce & Industry Systems","https://ramp.com"],
  ["Recruitee","Foundation","Ecommerce & Industry Systems","https://recruitee.com"],
  ["Rithum","Foundation","Ecommerce & Industry Systems","https://rithum.com"],
  ["Robin","Foundation","Ecommerce & Industry Systems","https://robinpowered.com"],
  ["Saleor","Foundation","Ecommerce & Industry Systems","https://saleor.io"],
  ["Sana Commerce","Foundation","Ecommerce & Industry Systems","https://sana-commerce.com"],
  ["SAP Concur","Foundation","Ecommerce & Industry Systems","https://concur.com"],
  ["ServiceTitan","Foundation","Ecommerce & Industry Systems","https://servicetitan.com"],
  ["Shopify","Foundation","Ecommerce & Industry Systems","https://shopify.com"],
  ["Shopware","Foundation","Ecommerce & Industry Systems","https://shopware.com"],
  ["SmartRecruiters (Posting API / Job Board API)","Foundation","Ecommerce & Industry Systems","https://smartrecruiters.com"],
  ["Spree Commerce","Foundation","Ecommerce & Industry Systems","https://spreecommerce.org"],
  ["Spryker","Foundation","Ecommerce & Industry Systems","https://spryker.com"],
  ["Swell","Foundation","Ecommerce & Industry Systems","https://swell.is"],
  ["Sylius","Foundation","Ecommerce & Industry Systems","https://sylius.com"],
  ["Teamleader","Foundation","Ecommerce & Industry Systems","https://teamleader.com"],
  ["Teamtailor","Foundation","Ecommerce & Industry Systems","https://teamtailor.com"],
  ["Trovata","Foundation","Ecommerce & Industry Systems","https://trovata.io"],
  ["Vena Solutions","Foundation","Ecommerce & Industry Systems","https://venasolutions.com"],
  ["Vendorful","Foundation","Ecommerce & Industry Systems","https://vendorful.com"],
  ["Vertex Inc.","Foundation","Ecommerce & Industry Systems","https://vertexinc.com"],
  ["VTEX","Foundation","Ecommerce & Industry Systems","https://vtex.com"],
  ["Walmart Marketplace","Foundation","Ecommerce & Industry Systems","https://walmart.com"],
  ["Wix Stores","Foundation","Ecommerce & Industry Systems","https://wix.com"],
  ["Workable","Foundation","Ecommerce & Industry Systems","https://workable.com"],
  ["Workday Adaptive Planning","Foundation","Ecommerce & Industry Systems","https://workday.com"],
  ["Zoho Commerce","Foundation","Ecommerce & Industry Systems","https://zoho.com"],
  ["Zoho Creator","Foundation","Ecommerce & Industry Systems","https://zoho.com"],
  ["Acumatica","Foundation","ERP & Finance","https://acumatica.com"],
  ["Certinia (formerly FinancialForce)","Foundation","ERP & Finance","https://certinia.com"],
  ["ERPNext (Frappe)","Foundation","ERP & Finance","https://frappe.io"],
  ["freee","Foundation","ERP & Finance","https://freee.co.jp"],
  ["Microsoft Dynamics 365 Business Central","Foundation","ERP & Finance","https://microsoft.com"],
  ["MYOB","Foundation","ERP & Finance","https://myob.com"],
  ["NetSuite","Foundation","ERP & Finance","https://netsuite.com"],
  ["Oracle Fusion Cloud ERP","Foundation","ERP & Finance","https://oracle.com"],
  ["QuickBooks Online","Foundation","ERP & Finance","https://intuit.com"],
  ["Sage Intacct","Foundation","ERP & Finance","https://sageintacct.com"],
  ["SAP Business One","Foundation","ERP & Finance","https://sap.com"],
  ["Workday Financial Management","Foundation","ERP & Finance","https://workday.com"],
  ["Xero","Foundation","ERP & Finance","https://xero.com"],
  ["Zoho Books","Foundation","ERP & Finance","https://zoho.com"],
  ["ADP","Foundation","HR & Payroll","https://adp.com"],
  ["BambooHR","Foundation","HR & Payroll","https://bamboohr.com"],
  ["Deel","Foundation","HR & Payroll","https://deel.com"],
  ["Factorial","Foundation","HR & Payroll","https://factorialhr.com"],
  ["Gusto","Foundation","HR & Payroll","https://gusto.com"],
  ["HiBob","Foundation","HR & Payroll","https://hibob.com"],
  ["Lattice","Foundation","HR & Payroll","https://lattice.com"],
  ["Namely","Foundation","HR & Payroll","https://namely.com"],
  ["Paychex","Foundation","HR & Payroll","https://paychex.com"],
  ["Paylocity","Foundation","HR & Payroll","https://paylocity.com"],
  ["Personio","Foundation","HR & Payroll","https://personio.com"],
  ["Remote (Remote.com)","Foundation","HR & Payroll","https://remote.com"],
  ["Rippling","Foundation","HR & Payroll","https://rippling.com"],
  ["SAP SuccessFactors","Foundation","HR & Payroll","https://sap.com"],
  ["TriNet","Foundation","HR & Payroll","https://trinet.com"],
  ["TriNet Zenefits (HR Platform)","Foundation","HR & Payroll","https://zenefits.com"],
  ["UKG (Ultimate Kronos Group)","Foundation","HR & Payroll","https://ukg.com"],
  ["Workday","Foundation","HR & Payroll","https://workday.com"],
  ["Alloy","Foundation","Identity & Access","https://alloy.com"],
  ["AWS Cognito","Foundation","Identity & Access","https://amazon.com"],
  ["BitGo Crypto-as-a-Service KYB","Foundation","Identity & Access","https://bitgo.com"],
  ["BitSight","Foundation","Identity & Access","https://bitsight.com"],
  ["bronID","Foundation","Identity & Access","https://bronid.com"],
  ["Clerk","Foundation","Identity & Access","https://clerk.com"],
  ["Cloudflare Access (Zero Trust)","Foundation","Identity & Access","https://cloudflare.com"],
  ["Conveyor","Foundation","Identity & Access","https://conveyor.com"],
  ["Cookiebot (Usercentrics)","Foundation","Identity & Access","https://cookiebot.com"],
  ["CrowdStrike Falcon","Foundation","Identity & Access","https://crowdstrike.com"],
  ["Descope","Foundation","Identity & Access","https://descope.com"],
  ["Didit","Foundation","Identity & Access","https://didit.me"],
  ["Didomi","Foundation","Identity & Access","https://didomi.io"],
  ["DomainTools","Foundation","Identity & Access","https://domaintools.com"],
  ["Dotfile","Foundation","Identity & Access","https://dotfile.com"],
  ["Drata","Foundation","Identity & Access","https://drata.com"],
  ["Duo Security","Foundation","Identity & Access","https://duo.com"],
  ["Ethyca","Foundation","Identity & Access","https://ethyca.com"],
  ["Feedly","Foundation","Identity & Access","https://feedly.com"],
  ["Frontegg","Foundation","Identity & Access","https://frontegg.com"],
  ["GitHub Advanced Security","Foundation","Identity & Access","https://github.com"],
  ["Google Workspace Admin SDK (Directory / SCIM Provisioning)","Foundation","Identity & Access","https://google.com"],
  ["HashiCorp Vault","Foundation","Identity & Access","https://hashicorp.com"],
  ["Hyperproof","Foundation","Identity & Access","https://hyperproof.io"],
  ["iDenfy","Foundation","Identity & Access","https://idenfy.com"],
  ["IPQualityScore","Foundation","Identity & Access","https://ipqualityscore.com"],
  ["Iubenda","Foundation","Identity & Access","https://iubenda.com"],
  ["JumpCloud","Foundation","Identity & Access","https://jumpcloud.com"],
  ["Keycloak","Foundation","Identity & Access","https://keycloak.org"],
  ["Kiteworks","Foundation","Identity & Access","https://kiteworks.com"],
  ["Know Your Customer (KnowYourCustomer.hk)","Foundation","Identity & Access","https://knowyourcustomer.hk"],
  ["Middesk","Foundation","Identity & Access","https://middesk.com"],
  ["Netskope","Foundation","Identity & Access","https://netskope.com"],
  ["Nightfall AI","Foundation","Identity & Access","https://nightfall.ai"],
  ["Okta","Foundation","Identity & Access","https://okta.com"],
  ["Oneleet","Foundation","Identity & Access","https://oneleet.com"],
  ["OneLogin","Foundation","Identity & Access","https://onelogin.com"],
  ["OneTrust","Foundation","Identity & Access","https://onetrust.com"],
  ["Ory","Foundation","Identity & Access","https://ory.sh"],
  ["Osano","Foundation","Identity & Access","https://osano.com"],
  ["Persona","Foundation","Identity & Access","https://withpersona.com"],
  ["Ping Identity","Foundation","Identity & Access","https://pingidentity.com"],
  ["RapidLEI","Foundation","Identity & Access","https://rapidlei.com"],
  ["SailPoint","Foundation","Identity & Access","https://sailpoint.com"],
  ["Secureframe","Foundation","Identity & Access","https://secureframe.com"],
  ["SecurityScorecard","Foundation","Identity & Access","https://securityscorecard.com"],
  ["SecurityTrails","Foundation","Identity & Access","https://securitytrails.com"],
  ["Shufti Pro","Foundation","Identity & Access","https://shuftipro.com"],
  ["Skyflow","Foundation","Identity & Access","https://skyflow.com"],
  ["Snyk","Foundation","Identity & Access","https://snyk.io"],
  ["Sprinto","Foundation","Identity & Access","https://sprinto.com"],
  ["Stytch","Foundation","Identity & Access","https://stytch.com"],
  ["Sumsub","Foundation","Identity & Access","https://sumsub.com"],
  ["Termly","Foundation","Identity & Access","https://termly.io"],
  ["The KYB (thekyb.com)","Foundation","Identity & Access","https://thekyb.com"],
  ["Transcend","Foundation","Identity & Access","https://transcend.io"],
  ["Trulioo","Foundation","Identity & Access","https://trulioo.com"],
  ["TrustCloud","Foundation","Identity & Access","https://trustcloud.ai"],
  ["UpGuard","Foundation","Identity & Access","https://upguard.com"],
  ["Vanta","Foundation","Identity & Access","https://vanta.com"],
  ["Vespia","Foundation","Identity & Access","https://vespia.io"],
  ["WorkOS","Foundation","Identity & Access","https://workos.com"],
  ["Zscaler","Foundation","Identity & Access","https://zscaler.com"],
]

// Local logo overrides (downloaded to public/); everything else comes from img.logo.dev as on the original.
export const LOGO_OVERRIDES = {
  "salesloft.com": "/assets/images/integrations/logos/salesloft.jpg",
  "gowindmill.com": "/assets/images/integrations/logos/windmill.jpg",
  "hginsights.com": "/assets/images/integrations/logos/hg-insights.jpg",
  "storeinspect.com": "/assets/images/integrations/logos/storeinspect.jpg",
  "knock2.ai": "/assets/images/integrations/logos/knock2.jpg",
  "leadmagic.io": "/assets/images/integrations/logos/leadmagic.jpg",
  "etropo.com": "/assets/images/integrations/logos/etropo.jpg",
  "friendbuy.com": "/assets/images/integrations/logos/friendbuy.jpg",
  "knowlarity.com": "/assets/images/integrations/logos/knowlarity.jpg",
  "airstride.ai": "/assets/images/integrations/logos/airstride.jpg",
  "findymail.com": "/assets/images/integrations/logos/findymail.jpg",
  "line.biz": "/assets/images/integrations/logos/line.jpg",
  "obvious.ai": "/assets/images/integrations/logos/obvious.jpg",
  "onesignal.com": "/assets/images/integrations/logos/onesignal.jpg",
  "pipecat.ai": "/assets/images/integrations/logos/pipecat.jpg",
  "postalytics.com": "/assets/images/integrations/logos/postalytics.jpg",
  "refiner.io": "/assets/images/integrations/logos/refiner.jpg",
  "spryker.com": "/assets/images/integrations/logos/spryker.jpg",
  "tidio.com": "/assets/images/integrations/logos/tidio.jpg",
  "zuddl.com": "/assets/images/integrations/logos/zuddl.jpg"
}
