#!/usr/bin/env python3
"""One-shot verification of the whole design-repo. Exit 1 on any FAIL.

    python3 extraction/verify_all.py                    # run every check
    python3 extraction/verify_all.py --citation-selftest   # prove the citation resolver on a synthetic tree
    python3 extraction/verify_all.py --update-counts    # recompute manifest `counts` + README count block, then exit

Stdlib + jsonschema. The repo root is derived from this file's location; the source project
(external evidence) is the folder ABOVE the repo root. When that sibling tree is absent, checks that
need it degrade to WARN (they are never silently passed as PASS).

Companion scripts (all must exist; checked by check m):
  extraction/build_schema.py  extraction/prove_drift.py  schema/tests/adversarial_test.py
  templates/verify_routes.py  compatibility/verify_rules.py  schema/semantic_validate.py
"""
import ast
import glob
import html
import importlib.util
import json
import os
import re
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.dirname(ROOT)  # source project = sibling tree one level up
HAVE_SRC = os.path.isdir(os.path.join(SRC, "src"))

CITE_KEYS = {"measuredFrom", "usedAt", "usedBy"}
CITE_RE = re.compile(r"([A-Za-z0-9_./@\[\]-]+\.[A-Za-z0-9]+):(\d+)(?:-(\d+))?")
COUNTS_BEGIN = "<!-- counts:begin (generated by extraction/verify_all.py --update-counts) -->"
COUNTS_END = "<!-- counts:end -->"
POLICY_ENUM = ["may-generate-new", "must-reuse-exact", "must-not-fabricate", "must-not-reuse-live-endpoint"]

RESULTS = []  # (status, check, message)


def rec(status, check, msg=""):
    RESULTS.append((status, check, msg))
    print(f"{status:4} [{check}] {msg}".rstrip())


def P(rel):
    return os.path.join(ROOT, rel)


def jload(rel):
    with open(P(rel), encoding="utf-8") as f:
        return json.load(f)


def all_json_files():
    out = []
    for dp, dn, fn in os.walk(ROOT):
        dn[:] = [d for d in dn if d not in ("__pycache__", ".git", "node_modules")]
        out += [os.path.join(dp, f) for f in fn if f.endswith(".json")]
    return sorted(out)


def load_module(name, rel):
    spec = importlib.util.spec_from_file_location(name, P(rel))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def py_functions(rel):
    with open(P(rel), encoding="utf-8") as f:
        tree = ast.parse(f.read())
    return {n.name for n in ast.walk(tree) if isinstance(n, ast.FunctionDef)}


# ------------------------------------------------------------------ citations
_line_cache = {}


def line_count(path):
    if path not in _line_cache:
        try:
            with open(path, encoding="utf-8", errors="replace") as f:
                _line_cache[path] = len(f.read().splitlines())
        except OSError:
            _line_cache[path] = None
    return _line_cache[path]


def check_citation(src_root, path, a, b=None):
    """Return None if `path:a[-b]` resolves inside src_root, else a reason string."""
    n = line_count(os.path.join(src_root, path))
    if n is None:
        return f"file missing: {path}"
    b = a if b is None else b
    if a < 1 or b < a:
        return f"bad range {path}:{a}-{b}"
    if b > n:
        return f"range exceeds file: {path}:{a}-{b} (file has {n} lines)"
    return None


def collect_citations(root):
    """Yield (jsonfile, jsonpath, citation-string) for every string under measuredFrom/usedAt/usedBy."""
    found = []

    def walk(x, f, p, inkey):
        if isinstance(x, dict):
            for k, v in x.items():
                walk(v, f, f"{p}.{k}", inkey or k in CITE_KEYS)
        elif isinstance(x, list):
            for i, v in enumerate(x):
                walk(v, f, f"{p}[{i}]", inkey)
        elif isinstance(x, str) and inkey:
            found.append((f, p, x))

    for fp in all_json_files():
        try:
            with open(fp, encoding="utf-8") as fh:
                walk(json.load(fh), os.path.relpath(fp, root), "", False)
        except ValueError:
            pass
    return found


def citation_selftest():
    ok = True
    with tempfile.TemporaryDirectory() as td:
        os.makedirs(os.path.join(td, "src"))
        with open(os.path.join(td, "src", "a.js"), "w") as f:
            f.write("\n".join(f"line {i}" for i in range(1, 11)) + "\n")  # 10 lines
        cases = [
            (("src/a.js", 1, 10), False, "full file"),
            (("src/a.js", 5, None), False, "single line"),
            (("src/a.js", 1, 11), True, "past EOF"),
            (("src/a.js", 11, None), True, "single line past EOF"),
            (("src/missing.js", 1, 2), True, "missing file"),
            (("src/a.js", 7, 3), True, "reversed range"),
            (("src/a.js", 0, 3), True, "zero start"),
        ]
        for args, should_fail, label in cases:
            r = check_citation(td, *args)
            good = (r is not None) == should_fail
            ok &= good
            print(f"{'ok  ' if good else 'BAD '} selftest {label}: {r or 'resolved'}")
    print("CITATION SELFTEST", "PASS" if ok else "FAIL")
    return 0 if ok else 1


# ------------------------------------------------------------------ counts
def count_leaves(x):
    """Token leaf = dict holding `value` (or `ref` for theme tokens)."""
    if isinstance(x, dict):
        if "value" in x or "ref" in x:
            return 1
        return sum(count_leaves(v) for k, v in x.items() if not k.startswith("$"))
    return 0


def layer_count(layer):
    n = 0
    for fp in sorted(glob.glob(P(f"tokens/{layer}/*.json"))):
        d = json.load(open(fp, encoding="utf-8"))
        n += sum(count_leaves(v) for k, v in d.items() if isinstance(v, dict) and k not in ("$description",))
    return n


def compute_counts():
    themes = {}
    for fp in sorted(glob.glob(P("tokens/themes/*.json"))):
        d = json.load(open(fp, encoding="utf-8"))
        themes[d["theme"]] = count_leaves(d["tokens"])
    tok = {"foundation": layer_count("00-foundation"), "semantic": layer_count("10-semantic"),
           "component": layer_count("20-component"), "layout": layer_count("30-layout")}
    tok["total"] = sum(tok.values())
    tok["themeResolved"] = themes
    routes = jload("templates/routes.json")
    al = jload("tokens/llm/component-allowlist.json")["components"]
    return {
        "tokens": tok,
        "primitives": len(glob.glob(P("primitives/*.json"))),
        "components": len(glob.glob(P("components/*.json"))),
        "sections": len(glob.glob(P("sections/*.json"))),
        "templates": len(jload("templates/templates.json")["templates"]),
        "routes": len(routes["routes"]),
        "routePatterns": sum(1 for r in routes["routes"] if ":" in r["path"]),
        "concreteUrls": sum(r["concreteUrlCount"] for r in routes["routes"]),
        "rules": len(jload("compatibility/graph.json")["rules"]),
        "assetRoles": len(jload("assets/asset-roles.json")["roles"]),
        "allowlistEntries": len(al),
    }


def counts_block(c):
    t = c["tokens"]
    rows = [
        ("Design tokens (foundation / semantic / component / layout)",
         f"{t['total']} ({t['foundation']} / {t['semantic']} / {t['component']} / {t['layout']})"),
        ("Resolved theme tokens (light / dark)", f"{t['themeResolved'].get('light')} / {t['themeResolved'].get('dark')}"),
        ("Primitives", c["primitives"]), ("Components", c["components"]), ("Sections", c["sections"]),
        ("Allowlist entries", c["allowlistEntries"]), ("Templates", c["templates"]),
        ("Route entries (incl. `*` catch-all)", c["routes"]),
        ("Parameterised route patterns", c["routePatterns"]),
        ("Concrete URLs", c["concreteUrls"]), ("Graph rules", c["rules"]), ("Asset roles", c["assetRoles"]),
    ]
    out = [COUNTS_BEGIN, "", "| Item | Count |", "|---|---|"]
    out += [f"| {a} | {b} |" for a, b in rows]
    out += ["", COUNTS_END]
    return "\n".join(out)


def update_counts():
    c = compute_counts()
    m = jload("registry.manifest.json")
    m["counts"] = c
    with open(P("registry.manifest.json"), "w", encoding="utf-8", newline="\n") as f:
        f.write(json.dumps(m, indent=2, ensure_ascii=False) + "\n")
    rp = P("README.md")
    txt = open(rp, encoding="utf-8").read()
    pat = re.compile(re.escape(COUNTS_BEGIN) + r".*?" + re.escape(COUNTS_END), re.S)
    if pat.search(txt):
        txt = pat.sub(lambda _m: counts_block(c), txt)
        with open(rp, "w", encoding="utf-8", newline="\n") as f:
            f.write(txt)
    print("updated manifest counts and README block")
    return 0


# ------------------------------------------------------------------ checks
def check_a():
    bad = 0
    files = all_json_files()
    for fp in files:
        try:
            json.load(open(fp, encoding="utf-8"))
        except ValueError as e:
            bad += 1
            rec("FAIL", "a.json-parse", f"{os.path.relpath(fp, ROOT)}: {e}")
    if not bad:
        rec("PASS", "a.json-parse", f"{len(files)} JSON files parse")


def check_b():
    import jsonschema
    schema, ex = jload("schema/pagespec.schema.json"), jload("schema/example.pagespec.json")
    try:
        jsonschema.Draft7Validator.check_schema(schema)
        rec("PASS", "b.schema-valid", "schema is valid Draft-07")
    except Exception as e:
        rec("FAIL", "b.schema-valid", str(e)[:300])
        return
    errs = list(jsonschema.Draft7Validator(schema).iter_errors(ex))
    rec("PASS" if not errs else "FAIL", "b.example-schema", f"{len(errs)} schema error(s)")
    sv = load_module("semantic_validate", "schema/semantic_validate.py")
    e, w = sv.validate(ex)
    rec("PASS" if not e else "FAIL", "b.example-semantic", f"{len(e)} error(s), {len(w)} warning(s) {e[:3] if e else ''}")


def check_c():
    bs = load_module("build_schema", "extraction/build_schema.py")
    fresh = json.dumps(bs.build(), indent=2, sort_keys=True, ensure_ascii=False) + "\n"
    disk = open(P("schema/pagespec.schema.json"), encoding="utf-8", newline="").read()
    rec("PASS" if fresh == disk else "FAIL", "c.schema-drift",
        "schema is byte-identical to build_schema.py output" if fresh == disk
        else "schema/pagespec.schema.json differs from a fresh build_schema.py run (re-run it, or the schema was hand-edited)")


def check_d():
    al = jload("tokens/llm/component-allowlist.json")["components"]
    ids = [e["id"] for e in al]
    bad = []
    if len(ids) != len(set(ids)):
        bad.append("duplicate allowlist ids")
    real = {}
    for d, kind in (("primitives", "primitive"), ("components", "component"), ("sections", "section")):
        for fp in glob.glob(P(f"{d}/*.json")):
            c = json.load(open(fp, encoding="utf-8"))
            real[c["id"]] = (kind, f"{d}/{os.path.basename(fp)}", c)
    for e in al:
        r = real.get(e["id"])
        if not r:
            bad.append(f"phantom allowlist entry (no contract): {e['id']}")
            continue
        if r[0] != e["kind"]:
            bad.append(f"{e['id']}: kind {e['kind']} != contract dir kind {r[0]}")
        if e["file"] != r[1]:
            bad.append(f"{e['id']}: file {e['file']} != real {r[1]}")
        if not os.path.isfile(P(e["file"])):
            bad.append(f"{e['id']}: file path missing {e['file']}")
        if e["kind"] == "section":
            keys = list(r[2]["content"]["fields"].keys())
            if sorted(e["settableProps"]) != sorted(keys):
                bad.append(f"{e['id']}: settableProps {sorted(e['settableProps'])} != contract content.fields {sorted(keys)}")
    for i, (kind, f, _) in real.items():
        if i not in ids:
            bad.append(f"orphan contract with no allowlist entry: {i} ({f})")
    for b in bad:
        rec("FAIL", "d.allowlist-parity", b)
    if not bad:
        rec("PASS", "d.allowlist-parity", f"{len(al)} allowlist entries == {len(real)} contracts; files exist; section settableProps == content.fields")


def check_e():
    if not HAVE_SRC:
        rec("WARN", "e.citations", "no sibling source tree (../src absent): citation-range check skipped")
        return
    cites = collect_citations(ROOT)
    bad, n = [], 0
    for f, p, s in cites:
        for m in CITE_RE.finditer(s):
            n += 1
            a = int(m.group(2))
            b = int(m.group(3)) if m.group(3) else None
            r = check_citation(SRC, m.group(1), a, b)
            if r:
                bad.append(f"{f}{p}: {r}")
    for b in bad[:60]:
        rec("FAIL", "e.citations", b)
    if len(bad) > 60:
        rec("FAIL", "e.citations", f"... {len(bad) - 60} more")
    if not bad:
        rec("PASS", "e.citations", f"{n} citations in {len(cites)} fields all resolve against the source tree")


def check_f():
    m, a = jload("registry.manifest.json"), jload("tokens/llm/component-allowlist.json")
    ok = m.get("allowlistVersion") == a.get("allowlistVersion") and m.get("allowlistVersion")
    rec("PASS" if ok else "FAIL", "f.allowlistVersion",
        f"manifest={m.get('allowlistVersion')!r} allowlist={a.get('allowlistVersion')!r}")


def check_g():
    m = jload("registry.manifest.json")
    real, got = compute_counts(), m.get("counts")
    if real == got:
        rec("PASS", "g.manifest-counts", f"counts block matches disk ({real['sections']} sections, {real['tokens']['total']} tokens, {real['concreteUrls']} URLs)")
        return
    def flat(d, p=""):
        return {f"{p}{k}": v for k, x in d.items() for k, v in (flat(x, f"{p}{k}.").items() if isinstance(x, dict) else [(k, x)])}
    fr, fg = flat(real), flat(got or {})
    for k in sorted(set(fr) | set(fg)):
        if fr.get(k) != fg.get(k):
            rec("FAIL", "g.manifest-counts", f"{k}: manifest={fg.get(k)} disk={fr.get(k)}")
    # concreteUrlTotals declared in routes.json must agree with the sum too
def check_g2():
    r = jload("templates/routes.json")
    t = r["concreteUrlTotals"]
    s = sum(x["concreteUrlCount"] for x in r["routes"])
    rec("PASS" if t["total"] == s and t["nonBlog"] + t["blog"] == t["total"] else "FAIL", "g.route-totals",
        f"declared total={t['total']} sum(routes)={s}")


def check_h():
    m = jload("registry.manifest.json")
    eps = m.get("entryPoints")
    flat = []
    def walk(x):
        if isinstance(x, str):
            flat.append(x)
        elif isinstance(x, dict):
            [walk(v) for v in x.values()]
        elif isinstance(x, list):
            [walk(v) for v in x]
    walk(eps)
    bad = []
    for e in flat:
        if os.path.isabs(e) or ".." in e.replace("\\", "/").split("/") or re.match(r"^[A-Za-z]:", e):
            bad.append(f"{e}: absolute or contains ..")
        elif not os.path.exists(P(e)):
            bad.append(f"{e}: does not exist inside the design-repo")
    if not flat:
        bad.append("entryPoints missing or empty")
    for b in bad:
        rec("FAIL", "h.entryPoints", b)
    if not bad:
        rec("PASS", "h.entryPoints", f"{len(flat)} entry points all exist inside the repo, none escape it")


TEXT_EXT = {".json", ".md", ".py", ".txt", ".yml", ".yaml", ".js", ".css", ".html", ".sh", ".toml", ".cfg", ""}
ABS_RE = re.compile("((?<![\\w.-])/Us" + "ers/|(?<![\\w.-])/ho" + "me/|\\b[A-Za-z]:\\\\)")


def check_i():
    bad = []
    for dp, dn, fn in os.walk(ROOT):
        dn[:] = [d for d in dn if d not in ("__pycache__", ".git", "node_modules")]
        for f in fn:
            if os.path.splitext(f)[1] not in TEXT_EXT or f == ".DS_Store":
                continue
            fp = os.path.join(dp, f)
            try:
                txt = open(fp, encoding="utf-8").read()
            except (UnicodeDecodeError, OSError):
                continue
            for i, line in enumerate(txt.splitlines(), 1):
                if ABS_RE.search(line):
                    bad.append(f"{os.path.relpath(fp, ROOT)}:{i}: absolute path")
    for b in bad[:40]:
        rec("FAIL", "i.no-absolute-paths", b)
    if not bad:
        rec("PASS", "i.no-absolute-paths", "no absolute local paths in any text file")


def collect_roles():
    used = set()
    def walk(x):
        if isinstance(x, dict):
            for k, v in x.items():
                if k == "assetRole":
                    if isinstance(v, str):
                        used.add(v)
                    elif isinstance(v, dict) and isinstance(v.get("const"), str):
                        used.add(v["const"])
                walk(v)
        elif isinstance(x, list):
            [walk(v) for v in x]
    for pat in ("sections/*.json", "primitives/*.json", "components/*.json", "schema/pagespec.schema.json"):
        for fp in glob.glob(P(pat)):
            walk(json.load(open(fp, encoding="utf-8")))
    schema = jload("schema/pagespec.schema.json")
    for k in schema["definitions"]:
        if k.startswith("assetRef."):
            used.add(k.split(".", 1)[1])
    return used


def check_j():
    ar = jload("assets/asset-roles.json")
    roles = set(ar["roles"])
    bad = [f"assetRole used but not in closed role list: {r}" for r in sorted(collect_roles() - roles)]
    enum = ar["generationPolicyEnum"]
    if enum != POLICY_ENUM:
        bad.append(f"generationPolicyEnum {enum} != expected 4-value enum")
    for r, spec in ar["roles"].items():
        if spec.get("generationPolicy") not in POLICY_ENUM:
            bad.append(f"role {r}: generationPolicy {spec.get('generationPolicy')!r} outside enum")
    for r, pin in ar["pinnedRoles"].items():
        if r.startswith("$"):
            continue
        if r not in roles:
            bad.append(f"pinned role {r} not in roles")
        elif ar["roles"][r].get("generationPolicy") != pin["generationPolicy"]:
            bad.append(f"pinned role {r}: generationPolicy is {ar['roles'][r].get('generationPolicy')!r}, pinned {pin['generationPolicy']!r}")
    for b in bad:
        rec("FAIL", "j.asset-roles", b)
    if not bad:
        rec("PASS", "j.asset-roles", f"{len(roles)} roles; all used roles closed; pinned values hold; policy enum ok")


def run(cmd, timeout=600):
    p = subprocess.run([sys.executable] + cmd, cwd=ROOT, capture_output=True, text=True, timeout=timeout)
    return p.returncode, (p.stdout + p.stderr).strip().splitlines()


def check_k():
    if HAVE_SRC:
        rc, out = run(["templates/verify_routes.py"])
        rec("PASS" if rc == 0 else "FAIL", "k.verify_routes", "exit 0" if rc == 0 else " | ".join(out[-6:]))
    else:
        rec("WARN", "k.verify_routes", "verify_routes.py reads ../src/App.jsx live and no source tree is present: skipped")
    rc, out = run(["compatibility/verify_rules.py"])
    rec("PASS" if rc == 0 else "FAIL", "k.verify_rules", "exit 0" if rc == 0 else " | ".join(out[-6:]))


def check_l():
    g = jload("compatibility/graph.json")["rules"]
    vr, sv = py_functions("compatibility/verify_rules.py"), py_functions("schema/semantic_validate.py")
    svm = load_module("semantic_validate_l", "schema/semantic_validate.py")
    bad = []
    for r in g:
        chk = (r.get("enforcedBy") or {}).get("check")
        if not chk:
            bad.append(f"{r['id']}: no enforcedBy.check")
            continue
        if chk not in vr:
            bad.append(f"{r['id']}: {chk} not a function in compatibility/verify_rules.py")
        if chk not in sv:
            bad.append(f"{r['id']}: {chk} not a function in schema/semantic_validate.py")
        if r["id"] not in svm.RULE_IDS:
            bad.append(f"{r['id']}: not in semantic_validate.RULE_IDS")
    for b in bad:
        rec("FAIL", "l.graph-validator", b)
    if not bad:
        rec("PASS", "l.graph-validator", f"{len(g)} rules: check function exists in both scripts and id is in RULE_IDS")


REF_RE = re.compile(r"(?<![\w./<-])((?:[\w.-]+/)*[\w.-]+\.(?:py|json|md|sh))\b")


def ref_exists(ref, base_dir=None):
    if "*" in ref or ref.startswith("http"):
        return True
    cands = [P(ref), os.path.join(SRC, ref)] + ([os.path.join(base_dir, ref)] if base_dir else [])
    if any(os.path.exists(c) for c in cands):
        return True
    base = os.path.basename(ref)
    if "/" not in ref:  # bare basename: accept a unique-enough match anywhere in the repo
        for dp, dn, fn in os.walk(ROOT):
            if base in fn:
                return True
    return False


def check_m():
    texts = []
    for rel in ("README.md", "CHANGELOG.md"):
        if os.path.isfile(P(rel)):
            texts.append((rel, open(P(rel), encoding="utf-8").read()))
    if os.path.isfile(P("registry.manifest.json")):
        texts.append(("registry.manifest.json", open(P("registry.manifest.json"), encoding="utf-8").read()))
    for fp in glob.glob(P("**/*.py"), recursive=True):
        try:
            d = ast.get_docstring(ast.parse(open(fp, encoding="utf-8").read()))
        except SyntaxError:
            d = None
        if d:
            texts.append((os.path.relpath(fp, ROOT), d))
    bad, warn, n = [], [], 0
    for src, t in texts:
        for m in REF_RE.finditer(t):
            ref = m.group(1)
            if ref.startswith("design-repo/"):
                ref = ref[len("design-repo/"):]
            n += 1
            if ref_exists(ref, os.path.dirname(P(src))):
                continue
            if not HAVE_SRC and (ref.startswith("src/") or ref in ("package.json", "CLONE_SPEC.md", "CLONE_ASSETS.md") or ref.endswith(".jsx")):
                continue
            if ref.startswith("schema/tests/") and not os.path.isdir(P("schema/tests")):
                warn.append(f"{src}: {ref}")
                continue
            if ref.startswith("src/") or ref.endswith((".jsx", ".js")):
                continue  # source-project evidence, not a package file
            bad.append(f"{src}: references missing file `{ref}`")
    for b in sorted(set(bad)):
        rec("FAIL", "m.referenced-files", b)
    for w in sorted(set(warn)):
        rec("WARN", "m.referenced-files", f"{w} (schema/tests missing)")
    if not bad:
        rec("PASS", "m.referenced-files", f"{n} file references in docstrings/README/CHANGELOG/manifest resolve")


def check_n():
    if not os.path.isfile(P("schema/tests/adversarial_test.py")):
        rec("WARN", "n.adversarial", "adversarial suite not present (schema/tests/adversarial_test.py)")
        return
    rc, out = run(["schema/tests/adversarial_test.py"])
    rec("PASS" if rc == 0 else "FAIL", "n.adversarial", (out[-1] if out else "exit 0") if rc == 0 else " | ".join(out[-6:]))


def check_o():
    schema, ex = jload("schema/pagespec.schema.json"), jload("schema/example.pagespec.json")
    branches = {}
    for b in schema["definitions"]["node"]["allOf"]:
        branches[b["if"]["properties"]["section"]["const"]] = b["then"]["properties"].get("content", {})

    def words(s):
        return len(html.unescape(re.sub(r"<[^>]+>", "", s)).split())

    over, count = [], [0]

    def walk(s, inst, path):
        if isinstance(s, dict) and "$ref" in s:
            cur = schema
            for part in s["$ref"][2:].split("/"):
                cur = cur[part]
            s = cur
        if not isinstance(s, dict):
            return
        if "x-maxWords" in s and isinstance(inst, str):
            count[0] += 1
            if words(inst) > s["x-maxWords"]:
                over.append(f"{path}: {words(inst)} words > {s['x-maxWords']}")
        if isinstance(inst, dict):
            for k, sub in (s.get("properties") or {}).items():
                if k in inst:
                    walk(sub, inst[k], f"{path}.{k}")
        if isinstance(inst, list) and isinstance(s.get("items"), dict):
            for j, x in enumerate(inst):
                walk(s["items"], x, f"{path}[{j}]")

    for i, node in enumerate(ex["nodes"]):
        walk(branches.get(node["section"], {}), node.get("content"), f"nodes[{i}]({node['section']})")
    for o in over:
        rec("FAIL", "o.maxWords", o)
    if not over:
        rec("PASS", "o.maxWords", f"{count[0]} budgeted string fields in the example are within x-maxWords")


def check_p():
    rp = P("README.md")
    if not os.path.isfile(rp):
        rec("FAIL", "p.readme-counts", "README.md missing")
        return
    txt = open(rp, encoding="utf-8").read()
    pat = re.compile(re.escape(COUNTS_BEGIN) + r".*?" + re.escape(COUNTS_END), re.S)
    m = pat.search(txt)
    if not m:
        rec("FAIL", "p.readme-counts", "README count block markers missing")
        return
    exp = counts_block(compute_counts())
    rec("PASS" if m.group(0) == exp else "FAIL", "p.readme-counts",
        "README count block matches disk" if m.group(0) == exp else "README count block is stale; run extraction/verify_all.py --update-counts")


def check_q():
    gi = P(".gitignore")
    need = ["design-repo.zip", "__pycache__/", "*.pyc", ".DS_Store"]
    have = open(gi).read().split() if os.path.isfile(gi) else []
    miss = [n for n in need if n not in have]
    rec("PASS" if not miss else "FAIL", "q.gitignore", "lists the zip, caches and .DS_Store" if not miss else f"missing entries: {miss}")
    m = jload("registry.manifest.json")
    ok = m.get("status") == "design-review-pending" and m.get("productionApproved") is False
    rec("PASS" if ok else "FAIL", "q.manifest-status", f"status={m.get('status')!r} productionApproved={m.get('productionApproved')!r}")
    themes = sorted(jload(f"tokens/themes/{os.path.basename(f)}")["theme"] for f in glob.glob(P("tokens/themes/*.json")))
    ok = sorted(m.get("schemaValidatedThemes", [])) == themes and m.get("defaultTheme") in themes
    rec("PASS" if ok else "FAIL", "q.manifest-themes", f"schemaValidatedThemes={m.get('schemaValidatedThemes')} files={themes} default={m.get('defaultTheme')}")


CHECKS = [check_a, check_b, check_c, check_d, check_e, check_f, check_g, check_g2, check_h, check_i, check_j,
          check_k, check_l, check_m, check_n, check_o, check_p, check_q]


def main(argv):
    if "--citation-selftest" in argv:
        return citation_selftest()
    if "--update-counts" in argv:
        return update_counts()
    print(f"design-repo verify_all  root={os.path.basename(ROOT)}  sibling source tree: {'present' if HAVE_SRC else 'ABSENT (graceful mode)'}")
    for fn in CHECKS:
        try:
            fn()
        except Exception as e:  # a crashing check is a failing check
            rec("FAIL", fn.__name__, f"check crashed: {type(e).__name__}: {e}")
    st = [r[0] for r in RESULTS]
    print(f"\nSUMMARY: {st.count('PASS')} PASS, {st.count('WARN')} WARN, {st.count('FAIL')} FAIL")
    print("RESULT:", "FAIL" if "FAIL" in st else "PASS")
    return 1 if "FAIL" in st else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
